export {
  type RegistryCatalogResponseDto,
  type RegistryPackageIndexResponseDto,
  type RegistryPackageRequestDto,
  type RegistryReadmeDto,
  type RegistrySourceDto,
  type RegistryVersionRefDto,
  type ResolvedRegistryVersionDto,
  type ResolveRegistryVersionRequestDto,
  registryCatalogResponseSchema,
  registryPackageIndexResponseSchema,
  registryPackageRequestSchema,
  registryReadmeSchema,
  registrySourceSchema,
  registryVersionRefSchema,
  resolvedRegistryVersionSchema,
  resolveRegistryVersionRequestSchema,
} from './schemas/version.js';
