import type {RunnersInterModuleClient} from '@shipfox/api-runners-dto/inter-module';
import {
  activateJobListenerActivity,
  bulkSetStepStatuses,
  createCancelRunnerJobsActivity,
  createEnqueueJobExecutionForRunner,
  createReleaseLeaseActivity,
  drainListenerEventsActivity,
  evaluateJobActivationsActivity,
  failJobExecutionAsTimedOutActivity,
  failRunAsTimedOutActivity,
  loadRunAttemptDag,
  peekListenerBufferActivity,
  recordListenerFiringOutcomeActivity,
  resolveJobListenerActivity,
  resolveJobStatusFromJobExecutionsActivity,
  resolveLeaseExpiredJobExecutionActivity,
  setJobExecutionStatus,
  setJobStatus,
  setRunAttemptStatus,
  settleListenerJobExecutionActivity,
} from './orchestration-activities.js';

export function createOrchestrationActivities(runners: RunnersInterModuleClient) {
  return {
    loadRunAttemptDag,
    setRunAttemptStatus,
    setJobStatus,
    setJobExecutionStatus,
    bulkSetStepStatuses,
    cancelRunnerJobsActivity: createCancelRunnerJobsActivity(runners),
    enqueueJobExecutionForRunner: createEnqueueJobExecutionForRunner(runners),
    evaluateJobActivationsActivity,
    failJobExecutionAsTimedOutActivity,
    failRunAsTimedOutActivity,
    activateJobListenerActivity,
    drainListenerEventsActivity,
    peekListenerBufferActivity,
    resolveJobListenerActivity,
    settleListenerJobExecutionActivity,
    recordListenerFiringOutcomeActivity,
    resolveLeaseExpiredJobExecutionActivity,
    resolveJobStatusFromJobExecutionsActivity,
    releaseLeaseActivity: createReleaseLeaseActivity(runners),
  };
}
