import {
  activateJobListenerActivity,
  bulkSetStepStatuses,
  cancelRunnerJobsActivity,
  drainListenerEventsActivity,
  enqueueJobExecutionForRunner,
  failJobExecutionAsTimedOutActivity,
  failRunAsTimedOutActivity,
  loadRunAttemptDag,
  recordListenerFiringOutcomeActivity,
  releaseLeaseActivity,
  resolveJobListenerActivity,
  resolveJobStatusFromJobExecutionsActivity,
  resolveLeaseExpiredJobExecutionActivity,
  setJobExecutionStatus,
  setJobStatus,
  setRunAttemptStatus,
  settleListenerJobExecutionActivity,
} from './orchestration-activities.js';

export function createOrchestrationActivities() {
  return {
    loadRunAttemptDag,
    setRunAttemptStatus,
    setJobStatus,
    setJobExecutionStatus,
    bulkSetStepStatuses,
    cancelRunnerJobsActivity,
    enqueueJobExecutionForRunner,
    failJobExecutionAsTimedOutActivity,
    failRunAsTimedOutActivity,
    activateJobListenerActivity,
    drainListenerEventsActivity,
    resolveJobListenerActivity,
    settleListenerJobExecutionActivity,
    recordListenerFiringOutcomeActivity,
    resolveLeaseExpiredJobExecutionActivity,
    resolveJobStatusFromJobExecutionsActivity,
    releaseLeaseActivity,
  };
}
