/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupLayoutRouteImport } from './routes/setup/_layout'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as WorkspacesWidLayoutRouteImport } from './routes/workspaces/$wid/_layout'
import { Route as IntegrationsGithubCallbackRouteImport } from './routes/integrations/github/callback'
import { Route as WorkspacesWidLayoutIndexRouteImport } from './routes/workspaces/$wid/_layout/index'
import { Route as SetupLayoutIntegrationsIndexRouteImport } from './routes/setup/_layout/integrations/index'
import { Route as SetupLayoutWorkspacesNewRouteImport } from './routes/setup/_layout/workspaces/new'
import { Route as SetupLayoutProjectsNewRouteImport } from './routes/setup/_layout/projects/new'
import { Route as SetupLayoutIntegrationsGithubRouteImport } from './routes/setup/_layout/integrations/github'
import { Route as SetupLayoutIntegrationsDebugRouteImport } from './routes/setup/_layout/integrations/debug'
import { Route as WorkspacesWidLayoutProjectsPidRouteImport } from './routes/workspaces/$wid/_layout/projects/$pid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupLayoutRoute = SetupLayoutRouteImport.update({
  id: '/setup/_layout',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWidLayoutRoute = WorkspacesWidLayoutRouteImport.update({
  id: '/workspaces/$wid/_layout',
  path: '/workspaces/$wid',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGithubCallbackRoute =
  IntegrationsGithubCallbackRouteImport.update({
    id: '/integrations/github/callback',
    path: '/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWidLayoutIndexRoute =
  WorkspacesWidLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWidLayoutRoute,
  } as any)
const SetupLayoutIntegrationsIndexRoute =
  SetupLayoutIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => SetupLayoutRoute,
  } as any)
const SetupLayoutWorkspacesNewRoute =
  SetupLayoutWorkspacesNewRouteImport.update({
    id: '/workspaces/new',
    path: '/workspaces/new',
    getParentRoute: () => SetupLayoutRoute,
  } as any)
const SetupLayoutProjectsNewRoute = SetupLayoutProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => SetupLayoutRoute,
} as any)
const SetupLayoutIntegrationsGithubRoute =
  SetupLayoutIntegrationsGithubRouteImport.update({
    id: '/integrations/github',
    path: '/integrations/github',
    getParentRoute: () => SetupLayoutRoute,
  } as any)
const SetupLayoutIntegrationsDebugRoute =
  SetupLayoutIntegrationsDebugRouteImport.update({
    id: '/integrations/debug',
    path: '/integrations/debug',
    getParentRoute: () => SetupLayoutRoute,
  } as any)
const WorkspacesWidLayoutProjectsPidRoute =
  WorkspacesWidLayoutProjectsPidRouteImport.update({
    id: '/projects/$pid',
    path: '/projects/$pid',
    getParentRoute: () => WorkspacesWidLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/setup': typeof SetupLayoutRouteWithChildren
  '/integrations/github/callback': typeof IntegrationsGithubCallbackRoute
  '/workspaces/$wid': typeof WorkspacesWidLayoutRouteWithChildren
  '/setup/integrations/debug': typeof SetupLayoutIntegrationsDebugRoute
  '/setup/integrations/github': typeof SetupLayoutIntegrationsGithubRoute
  '/setup/projects/new': typeof SetupLayoutProjectsNewRoute
  '/setup/workspaces/new': typeof SetupLayoutWorkspacesNewRoute
  '/setup/integrations/': typeof SetupLayoutIntegrationsIndexRoute
  '/workspaces/$wid/': typeof WorkspacesWidLayoutIndexRoute
  '/workspaces/$wid/projects/$pid': typeof WorkspacesWidLayoutProjectsPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/setup': typeof SetupLayoutRouteWithChildren
  '/integrations/github/callback': typeof IntegrationsGithubCallbackRoute
  '/setup/integrations/debug': typeof SetupLayoutIntegrationsDebugRoute
  '/setup/integrations/github': typeof SetupLayoutIntegrationsGithubRoute
  '/setup/projects/new': typeof SetupLayoutProjectsNewRoute
  '/setup/workspaces/new': typeof SetupLayoutWorkspacesNewRoute
  '/setup/integrations': typeof SetupLayoutIntegrationsIndexRoute
  '/workspaces/$wid': typeof WorkspacesWidLayoutIndexRoute
  '/workspaces/$wid/projects/$pid': typeof WorkspacesWidLayoutProjectsPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/setup/_layout': typeof SetupLayoutRouteWithChildren
  '/integrations/github/callback': typeof IntegrationsGithubCallbackRoute
  '/workspaces/$wid/_layout': typeof WorkspacesWidLayoutRouteWithChildren
  '/setup/_layout/integrations/debug': typeof SetupLayoutIntegrationsDebugRoute
  '/setup/_layout/integrations/github': typeof SetupLayoutIntegrationsGithubRoute
  '/setup/_layout/projects/new': typeof SetupLayoutProjectsNewRoute
  '/setup/_layout/workspaces/new': typeof SetupLayoutWorkspacesNewRoute
  '/setup/_layout/integrations/': typeof SetupLayoutIntegrationsIndexRoute
  '/workspaces/$wid/_layout/': typeof WorkspacesWidLayoutIndexRoute
  '/workspaces/$wid/_layout/projects/$pid': typeof WorkspacesWidLayoutProjectsPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/setup'
    | '/integrations/github/callback'
    | '/workspaces/$wid'
    | '/setup/integrations/debug'
    | '/setup/integrations/github'
    | '/setup/projects/new'
    | '/setup/workspaces/new'
    | '/setup/integrations/'
    | '/workspaces/$wid/'
    | '/workspaces/$wid/projects/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/setup'
    | '/integrations/github/callback'
    | '/setup/integrations/debug'
    | '/setup/integrations/github'
    | '/setup/projects/new'
    | '/setup/workspaces/new'
    | '/setup/integrations'
    | '/workspaces/$wid'
    | '/workspaces/$wid/projects/$pid'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/setup/_layout'
    | '/integrations/github/callback'
    | '/workspaces/$wid/_layout'
    | '/setup/_layout/integrations/debug'
    | '/setup/_layout/integrations/github'
    | '/setup/_layout/projects/new'
    | '/setup/_layout/workspaces/new'
    | '/setup/_layout/integrations/'
    | '/workspaces/$wid/_layout/'
    | '/workspaces/$wid/_layout/projects/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  SetupLayoutRoute: typeof SetupLayoutRouteWithChildren
  IntegrationsGithubCallbackRoute: typeof IntegrationsGithubCallbackRoute
  WorkspacesWidLayoutRoute: typeof WorkspacesWidLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/_layout': {
      id: '/setup/_layout'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$wid/_layout': {
      id: '/workspaces/$wid/_layout'
      path: '/workspaces/$wid'
      fullPath: '/workspaces/$wid'
      preLoaderRoute: typeof WorkspacesWidLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/github/callback': {
      id: '/integrations/github/callback'
      path: '/integrations/github/callback'
      fullPath: '/integrations/github/callback'
      preLoaderRoute: typeof IntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$wid/_layout/': {
      id: '/workspaces/$wid/_layout/'
      path: '/'
      fullPath: '/workspaces/$wid/'
      preLoaderRoute: typeof WorkspacesWidLayoutIndexRouteImport
      parentRoute: typeof WorkspacesWidLayoutRoute
    }
    '/setup/_layout/integrations/': {
      id: '/setup/_layout/integrations/'
      path: '/integrations'
      fullPath: '/setup/integrations/'
      preLoaderRoute: typeof SetupLayoutIntegrationsIndexRouteImport
      parentRoute: typeof SetupLayoutRoute
    }
    '/setup/_layout/workspaces/new': {
      id: '/setup/_layout/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/setup/workspaces/new'
      preLoaderRoute: typeof SetupLayoutWorkspacesNewRouteImport
      parentRoute: typeof SetupLayoutRoute
    }
    '/setup/_layout/projects/new': {
      id: '/setup/_layout/projects/new'
      path: '/projects/new'
      fullPath: '/setup/projects/new'
      preLoaderRoute: typeof SetupLayoutProjectsNewRouteImport
      parentRoute: typeof SetupLayoutRoute
    }
    '/setup/_layout/integrations/github': {
      id: '/setup/_layout/integrations/github'
      path: '/integrations/github'
      fullPath: '/setup/integrations/github'
      preLoaderRoute: typeof SetupLayoutIntegrationsGithubRouteImport
      parentRoute: typeof SetupLayoutRoute
    }
    '/setup/_layout/integrations/debug': {
      id: '/setup/_layout/integrations/debug'
      path: '/integrations/debug'
      fullPath: '/setup/integrations/debug'
      preLoaderRoute: typeof SetupLayoutIntegrationsDebugRouteImport
      parentRoute: typeof SetupLayoutRoute
    }
    '/workspaces/$wid/_layout/projects/$pid': {
      id: '/workspaces/$wid/_layout/projects/$pid'
      path: '/projects/$pid'
      fullPath: '/workspaces/$wid/projects/$pid'
      preLoaderRoute: typeof WorkspacesWidLayoutProjectsPidRouteImport
      parentRoute: typeof WorkspacesWidLayoutRoute
    }
  }
}

interface SetupLayoutRouteChildren {
  SetupLayoutIntegrationsDebugRoute: typeof SetupLayoutIntegrationsDebugRoute
  SetupLayoutIntegrationsGithubRoute: typeof SetupLayoutIntegrationsGithubRoute
  SetupLayoutProjectsNewRoute: typeof SetupLayoutProjectsNewRoute
  SetupLayoutWorkspacesNewRoute: typeof SetupLayoutWorkspacesNewRoute
  SetupLayoutIntegrationsIndexRoute: typeof SetupLayoutIntegrationsIndexRoute
}

const SetupLayoutRouteChildren: SetupLayoutRouteChildren = {
  SetupLayoutIntegrationsDebugRoute: SetupLayoutIntegrationsDebugRoute,
  SetupLayoutIntegrationsGithubRoute: SetupLayoutIntegrationsGithubRoute,
  SetupLayoutProjectsNewRoute: SetupLayoutProjectsNewRoute,
  SetupLayoutWorkspacesNewRoute: SetupLayoutWorkspacesNewRoute,
  SetupLayoutIntegrationsIndexRoute: SetupLayoutIntegrationsIndexRoute,
}

const SetupLayoutRouteWithChildren = SetupLayoutRoute._addFileChildren(
  SetupLayoutRouteChildren,
)

interface WorkspacesWidLayoutRouteChildren {
  WorkspacesWidLayoutIndexRoute: typeof WorkspacesWidLayoutIndexRoute
  WorkspacesWidLayoutProjectsPidRoute: typeof WorkspacesWidLayoutProjectsPidRoute
}

const WorkspacesWidLayoutRouteChildren: WorkspacesWidLayoutRouteChildren = {
  WorkspacesWidLayoutIndexRoute: WorkspacesWidLayoutIndexRoute,
  WorkspacesWidLayoutProjectsPidRoute: WorkspacesWidLayoutProjectsPidRoute,
}

const WorkspacesWidLayoutRouteWithChildren =
  WorkspacesWidLayoutRoute._addFileChildren(WorkspacesWidLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  SetupLayoutRoute: SetupLayoutRouteWithChildren,
  IntegrationsGithubCallbackRoute: IntegrationsGithubCallbackRoute,
  WorkspacesWidLayoutRoute: WorkspacesWidLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
