/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SetupIntegrationsIndexRouteImport } from './routes/setup/integrations/index'
import { Route as SetupProjectsNewRouteImport } from './routes/setup/projects/new'
import { Route as SetupIntegrationsGithubRouteImport } from './routes/setup/integrations/github'
import { Route as SetupIntegrationsDebugRouteImport } from './routes/setup/integrations/debug'
import { Route as IntegrationsGithubCallbackRouteImport } from './routes/integrations/github/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIntegrationsIndexRoute = SetupIntegrationsIndexRouteImport.update({
  id: '/setup/integrations/',
  path: '/setup/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProjectsNewRoute = SetupProjectsNewRouteImport.update({
  id: '/setup/projects/new',
  path: '/setup/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIntegrationsGithubRoute = SetupIntegrationsGithubRouteImport.update({
  id: '/setup/integrations/github',
  path: '/setup/integrations/github',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIntegrationsDebugRoute = SetupIntegrationsDebugRouteImport.update({
  id: '/setup/integrations/debug',
  path: '/setup/integrations/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGithubCallbackRoute =
  IntegrationsGithubCallbackRouteImport.update({
    id: '/integrations/github/callback',
    path: '/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/integrations/github/callback': typeof IntegrationsGithubCallbackRoute
  '/setup/integrations/debug': typeof SetupIntegrationsDebugRoute
  '/setup/integrations/github': typeof SetupIntegrationsGithubRoute
  '/setup/projects/new': typeof SetupProjectsNewRoute
  '/setup/integrations/': typeof SetupIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/integrations/github/callback': typeof IntegrationsGithubCallbackRoute
  '/setup/integrations/debug': typeof SetupIntegrationsDebugRoute
  '/setup/integrations/github': typeof SetupIntegrationsGithubRoute
  '/setup/projects/new': typeof SetupProjectsNewRoute
  '/setup/integrations': typeof SetupIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/integrations/github/callback': typeof IntegrationsGithubCallbackRoute
  '/setup/integrations/debug': typeof SetupIntegrationsDebugRoute
  '/setup/integrations/github': typeof SetupIntegrationsGithubRoute
  '/setup/projects/new': typeof SetupProjectsNewRoute
  '/setup/integrations/': typeof SetupIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/projects/$projectId'
    | '/integrations/github/callback'
    | '/setup/integrations/debug'
    | '/setup/integrations/github'
    | '/setup/projects/new'
    | '/setup/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/projects/$projectId'
    | '/integrations/github/callback'
    | '/setup/integrations/debug'
    | '/setup/integrations/github'
    | '/setup/projects/new'
    | '/setup/integrations'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/projects/$projectId'
    | '/integrations/github/callback'
    | '/setup/integrations/debug'
    | '/setup/integrations/github'
    | '/setup/projects/new'
    | '/setup/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  IntegrationsGithubCallbackRoute: typeof IntegrationsGithubCallbackRoute
  SetupIntegrationsDebugRoute: typeof SetupIntegrationsDebugRoute
  SetupIntegrationsGithubRoute: typeof SetupIntegrationsGithubRoute
  SetupProjectsNewRoute: typeof SetupProjectsNewRoute
  SetupIntegrationsIndexRoute: typeof SetupIntegrationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/integrations/': {
      id: '/setup/integrations/'
      path: '/setup/integrations'
      fullPath: '/setup/integrations/'
      preLoaderRoute: typeof SetupIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/projects/new': {
      id: '/setup/projects/new'
      path: '/setup/projects/new'
      fullPath: '/setup/projects/new'
      preLoaderRoute: typeof SetupProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/integrations/github': {
      id: '/setup/integrations/github'
      path: '/setup/integrations/github'
      fullPath: '/setup/integrations/github'
      preLoaderRoute: typeof SetupIntegrationsGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/integrations/debug': {
      id: '/setup/integrations/debug'
      path: '/setup/integrations/debug'
      fullPath: '/setup/integrations/debug'
      preLoaderRoute: typeof SetupIntegrationsDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/github/callback': {
      id: '/integrations/github/callback'
      path: '/integrations/github/callback'
      fullPath: '/integrations/github/callback'
      preLoaderRoute: typeof IntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  IntegrationsGithubCallbackRoute: IntegrationsGithubCallbackRoute,
  SetupIntegrationsDebugRoute: SetupIntegrationsDebugRoute,
  SetupIntegrationsGithubRoute: SetupIntegrationsGithubRoute,
  SetupProjectsNewRoute: SetupProjectsNewRoute,
  SetupIntegrationsIndexRoute: SetupIntegrationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
