min_version = "2026.5.18"

[tools]
gh = "2.94.0"
"node"      = "24.17.0"
"npm:pnpm"  = "11.6.0"
"npm:turbo" = "2.9.18"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
lockfile       = true
minimum_release_age = "48h"
