[tools]
gh = "2.92.0"
"node"      = "24.15.0"
"npm:pnpm"  = "10.33.0"
"npm:turbo" = "2.9.12"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
lockfile       = true
install_before = "48h"
