strictPeerDependencies: true
dedupePeerDependents: true
nodeLinker: isolated
minimumReleaseAge: 2880
allowBuilds:
  '@google/genai': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  sharp: true

packages:
  - "apps/*"
  - "e2e/**"
  - "libs/**"
  - "infra/**"
  - "tools/**"
  - "turbo/**"
  - "!**/vite/types/**"
  - "!**/node_modules/**"
