strictPeerDependencies: true
dedupePeerDependents: true
nodeLinker: isolated
minimumReleaseAge: 2880
allowBuilds:
  '@google/genai': true
  '@swc/core': true
  core-js: false
  cpu-features: true
  esbuild: true
  koffi: true
  protobufjs: true
  sharp: true
  ssh2: true

packages:
  - "apps/*"
  - "e2e/**"
  - "libs/**"
  - "infra/**"
  - "tools/**"
  - "turbo/**"
  - "!libs/client/shell/test/external/fixture/**"
  - "!**/vite/types/**"
  - "!**/node_modules/**"
