// GENERATED by @shipfox/client-shell/vite. Do not edit.
// biome-ignore-all format: generated code has stable, reviewable output.
// biome-ignore-all assist/source/organizeImports: generated imports follow route order.
import {createRoute, createRouter} from '@tanstack/react-router';
import {assertRouteImplFrame, buildAnchorSkeleton, parseAppSearch, stringifyAppSearch, type RouteImpl, type RouterContext} from '@shipfox/client-shell/runtime';
import * as route0Module from "@shipfox/client-auth/routes/index";
import * as route1Module from "@shipfox/client-auth/routes/login";
import * as route2Module from "@shipfox/client-auth/routes/logout";
import * as route3Module from "@shipfox/client-auth/routes/reset";
import * as route4Module from "@shipfox/client-auth/routes/signup";
import * as route5Module from "@shipfox/client-auth/routes/workspace-onboarding";
import * as route6Module from "@shipfox/client-invitations/routes/accept";
import * as route7Module from "@shipfox/client-integrations/routes/github-callback";
import * as route8Module from "@shipfox/client-integrations/routes/linear-callback";
import * as route9Module from "@shipfox/client-integrations/routes/jira-callback";
import * as route10Module from "@shipfox/client-integrations/routes/sentry-callback";
import * as route11Module from "@shipfox/client-integrations/routes/slack-callback";
import * as route12Module from "@shipfox/client-integrations/routes/integrations";
import * as route13Module from "@shipfox/client-integrations/routes/gitea";
import * as route14Module from "@shipfox/client-integrations/routes/github";
import * as route15Module from "@shipfox/client-integrations/routes/linear";
import * as route16Module from "@shipfox/client-integrations/routes/jira";
import * as route17Module from "@shipfox/client-integrations/routes/sentry";
import * as route18Module from "@shipfox/client-integrations/routes/slack";
import * as route19Module from "@shipfox/client-integrations/routes/integrations-settings";
import * as route20Module from "@shipfox/client-integrations/routes/connection-details";
import * as route21Module from "@shipfox/client-projects/routes/home";
import * as route22Module from "@shipfox/client-projects/routes/create-project";
import * as route23Module from "@shipfox/client-projects/routes/project-index";
import * as route24Module from "@shipfox/client-projects/routes/project-settings-index";
import * as route25Module from "@shipfox/client-projects/routes/project-settings";
import * as route26Module from "@shipfox/client-workflows/routes/workflows";
import * as route27Module from "@shipfox/client-workflows/routes/runs";
import * as route28Module from "@shipfox/client-workflows/routes/run-detail";
import * as route29Module from "@shipfox/client-workflows/routes/job-detail";
import * as route30Module from "@shipfox/client-agent/routes/model-provider";
import * as route31Module from "@shipfox/client-agent/routes/agents-settings";
import * as route32Module from "@shipfox/client-agent/routes/agent-access-consent";
import * as route33Module from "@shipfox/client-agent/routes/agent-access-settings";
import * as route34Module from "@shipfox/client-runners/routes/runners-settings";
import * as route35Module from "@shipfox/client-runners/routes/provisioners-settings";
import * as route36Module from "@shipfox/client-secrets/routes/secrets-settings";
import * as route37Module from "@shipfox/client-secrets/routes/variables-settings";
import * as route38Module from "@shipfox/client-triggers/routes/events-settings";
import * as route39Module from "@shipfox/client-workspace-settings/routes/index";
import * as route40Module from "@shipfox/client-workspace-settings/routes/members";
import * as route41Module from "@shipfox/client-workspace-settings/routes/general";

function routeOptions<T extends RouteImpl>(routeImpl: T, impl: string, path: string): T['options'] {
  assertRouteImplFrame(routeImpl, impl, path);
  return routeImpl.options;
}

const skeleton = buildAnchorSkeleton({
  navigation: [
    {
      "id": "nav.projects",
      "scope": "workspace",
      "label": "Projects",
      "to": "/w/$workspaceSlug",
      "exact": true,
      "order": 100
    },
    {
      "id": "nav.runs",
      "scope": "project",
      "label": "Runs",
      "to": "/w/$workspaceSlug/p/$projectSlug/runs",
      "order": 100
    },
    {
      "id": "nav.workflows",
      "scope": "project",
      "label": "Workflows",
      "to": "/w/$workspaceSlug/p/$projectSlug/workflows",
      "order": 200
    },
    {
      "id": "nav.settings",
      "scope": "workspace",
      "label": "Settings",
      "to": "/w/$workspaceSlug/settings",
      "order": 200
    }
  ],
  settingsSections: [
    {
      "id": "settings.project-general",
      "scope": "project",
      "pathSegment": "general",
      "label": "General",
      "icon": "settings3Line",
      "order": 50
    },
    {
      "id": "settings.general",
      "pathSegment": "general",
      "label": "General",
      "icon": "settings3Line",
      "order": 50,
      "scope": "workspace"
    },
    {
      "id": "settings.members",
      "pathSegment": "members",
      "label": "Members",
      "icon": "userLine",
      "order": 100,
      "scope": "workspace"
    },
    {
      "id": "settings.runners",
      "pathSegment": "runners",
      "label": "Runners",
      "icon": "settings3Line",
      "order": 200,
      "scope": "workspace"
    },
    {
      "id": "settings.provisioners",
      "pathSegment": "provisioners",
      "label": "Runner provisioners",
      "icon": "serverLine",
      "order": 300,
      "scope": "workspace"
    },
    {
      "id": "settings.agents",
      "pathSegment": "agents",
      "label": "Agents",
      "icon": "robot2Line",
      "order": 400,
      "scope": "workspace"
    },
    {
      "id": "settings.agent-access",
      "pathSegment": "agent-access",
      "label": "MCP connections",
      "icon": "terminalBoxLine",
      "order": 450,
      "scope": "workspace"
    },
    {
      "id": "settings.secrets",
      "pathSegment": "secrets",
      "label": "Secrets",
      "icon": "keyLine",
      "order": 500,
      "scope": "workspace"
    },
    {
      "id": "settings.variables",
      "pathSegment": "variables",
      "label": "Variables",
      "icon": "bracesLine",
      "order": 600,
      "scope": "workspace"
    },
    {
      "id": "settings.integrations",
      "pathSegment": "integrations",
      "label": "Integrations",
      "icon": "plugLine",
      "order": 700,
      "scope": "workspace"
    },
    {
      "id": "settings.events",
      "pathSegment": "events",
      "label": "Events",
      "icon": "pulseLine",
      "order": 800,
      "scope": "workspace"
    }
  ],
});

const route0 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/",
  ...routeOptions(route0Module.default, "@shipfox/client-auth/routes/index", "/"),
});

const route1 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/login",
  ...routeOptions(route1Module.default, "@shipfox/client-auth/routes/login", "/auth/login"),
});

const route2 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/logout",
  ...routeOptions(route2Module.default, "@shipfox/client-auth/routes/logout", "/auth/logout"),
});

const route3 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/reset",
  ...routeOptions(route3Module.default, "@shipfox/client-auth/routes/reset", "/auth/reset"),
});

const route4 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/signup",
  ...routeOptions(route4Module.default, "@shipfox/client-auth/routes/signup", "/auth/signup"),
});

const route5 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/setup/workspaces/new",
  ...routeOptions(route5Module.default, "@shipfox/client-auth/routes/workspace-onboarding", "/setup/workspaces/new"),
});

const route6 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/invitations/accept",
  ...routeOptions(route6Module.default, "@shipfox/client-invitations/routes/accept", "/invitations/accept"),
});

const route7 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/github/callback",
  ...routeOptions(route7Module.default, "@shipfox/client-integrations/routes/github-callback", "/integrations/github/callback"),
});

const route8 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/linear/callback",
  ...routeOptions(route8Module.default, "@shipfox/client-integrations/routes/linear-callback", "/integrations/linear/callback"),
});

const route9 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/jira/callback",
  ...routeOptions(route9Module.default, "@shipfox/client-integrations/routes/jira-callback", "/integrations/jira/callback"),
});

const route10 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/sentry/callback",
  ...routeOptions(route10Module.default, "@shipfox/client-integrations/routes/sentry-callback", "/integrations/sentry/callback"),
});

const route11 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/slack/callback",
  ...routeOptions(route11Module.default, "@shipfox/client-integrations/routes/slack-callback", "/integrations/slack/callback"),
});

const route12 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations",
  ...routeOptions(route12Module.default, "@shipfox/client-integrations/routes/integrations", "/w/$workspaceSlug/integrations"),
});

const route13 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/gitea",
  ...routeOptions(route13Module.default, "@shipfox/client-integrations/routes/gitea", "/w/$workspaceSlug/integrations/gitea"),
});

const route14 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/github",
  ...routeOptions(route14Module.default, "@shipfox/client-integrations/routes/github", "/w/$workspaceSlug/integrations/github"),
});

const route15 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/linear",
  ...routeOptions(route15Module.default, "@shipfox/client-integrations/routes/linear", "/w/$workspaceSlug/integrations/linear"),
});

const route16 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/jira",
  ...routeOptions(route16Module.default, "@shipfox/client-integrations/routes/jira", "/w/$workspaceSlug/integrations/jira"),
});

const route17 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/sentry",
  ...routeOptions(route17Module.default, "@shipfox/client-integrations/routes/sentry", "/w/$workspaceSlug/integrations/sentry"),
});

const route18 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/slack",
  ...routeOptions(route18Module.default, "@shipfox/client-integrations/routes/slack", "/w/$workspaceSlug/integrations/slack"),
});

const route19 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/integrations",
  ...routeOptions(route19Module.default, "@shipfox/client-integrations/routes/integrations-settings", "/w/$workspaceSlug/settings/integrations"),
});

const route20 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/integrations/$connectionSlug",
  ...routeOptions(route20Module.default, "@shipfox/client-integrations/routes/connection-details", "/w/$workspaceSlug/settings/integrations/$connectionSlug"),
});

const route21 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/",
  ...routeOptions(route21Module.default, "@shipfox/client-projects/routes/home", "/w/$workspaceSlug"),
});

const route22 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/projects/new",
  ...routeOptions(route22Module.default, "@shipfox/client-projects/routes/create-project", "/w/$workspaceSlug/projects/new"),
});

const route23 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/",
  ...routeOptions(route23Module.default, "@shipfox/client-projects/routes/project-index", "/w/$workspaceSlug/p/$projectSlug"),
});

const route24 = createRoute({
  getParentRoute: () => skeleton.projectSettings,
  path: "/",
  ...routeOptions(route24Module.default, "@shipfox/client-projects/routes/project-settings-index", "/w/$workspaceSlug/p/$projectSlug/settings"),
});

const route25 = createRoute({
  getParentRoute: () => skeleton.projectSettings,
  path: "/general",
  ...routeOptions(route25Module.default, "@shipfox/client-projects/routes/project-settings", "/w/$workspaceSlug/p/$projectSlug/settings/general"),
});

const route26 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/workflows",
  ...routeOptions(route26Module.default, "@shipfox/client-workflows/routes/workflows", "/w/$workspaceSlug/p/$projectSlug/workflows"),
});

const route27 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/runs",
  ...routeOptions(route27Module.default, "@shipfox/client-workflows/routes/runs", "/w/$workspaceSlug/p/$projectSlug/runs"),
});

const route28 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/runs/$workflowRunId",
  ...routeOptions(route28Module.default, "@shipfox/client-workflows/routes/run-detail", "/w/$workspaceSlug/p/$projectSlug/runs/$workflowRunId"),
});

const route29 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/runs/$workflowRunId/jobs/$jobId",
  ...routeOptions(route29Module.default, "@shipfox/client-workflows/routes/job-detail", "/w/$workspaceSlug/p/$projectSlug/runs/$workflowRunId/jobs/$jobId"),
});

const route30 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/model-provider",
  ...routeOptions(route30Module.default, "@shipfox/client-agent/routes/model-provider", "/w/$workspaceSlug/model-provider"),
});

const route31 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/agents",
  ...routeOptions(route31Module.default, "@shipfox/client-agent/routes/agents-settings", "/w/$workspaceSlug/settings/agents"),
});

const route32 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/oauth/consent",
  ...routeOptions(route32Module.default, "@shipfox/client-agent/routes/agent-access-consent", "/oauth/consent"),
});

const route33 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/agent-access",
  ...routeOptions(route33Module.default, "@shipfox/client-agent/routes/agent-access-settings", "/w/$workspaceSlug/settings/agent-access"),
});

const route34 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/runners",
  ...routeOptions(route34Module.default, "@shipfox/client-runners/routes/runners-settings", "/w/$workspaceSlug/settings/runners"),
});

const route35 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/provisioners",
  ...routeOptions(route35Module.default, "@shipfox/client-runners/routes/provisioners-settings", "/w/$workspaceSlug/settings/provisioners"),
});

const route36 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/secrets",
  ...routeOptions(route36Module.default, "@shipfox/client-secrets/routes/secrets-settings", "/w/$workspaceSlug/settings/secrets"),
});

const route37 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/variables",
  ...routeOptions(route37Module.default, "@shipfox/client-secrets/routes/variables-settings", "/w/$workspaceSlug/settings/variables"),
});

const route38 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/events",
  ...routeOptions(route38Module.default, "@shipfox/client-triggers/routes/events-settings", "/w/$workspaceSlug/settings/events"),
});

const route39 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/",
  ...routeOptions(route39Module.default, "@shipfox/client-workspace-settings/routes/index", "/w/$workspaceSlug/settings"),
});

const route40 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/members",
  ...routeOptions(route40Module.default, "@shipfox/client-workspace-settings/routes/members", "/w/$workspaceSlug/settings/members"),
});

const route41 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/general",
  ...routeOptions(route41Module.default, "@shipfox/client-workspace-settings/routes/general", "/w/$workspaceSlug/settings/general"),
});

const projectSettings = skeleton.projectSettings.addChildren([route24, route25]);
const projectLayout = skeleton.projectLayout.addChildren([route23, route26, route27, route28, route29,
  projectSettings]);
const workspaceSettings = skeleton.workspaceSettings.addChildren([route19, route20, route31, route33, route34, route35, route36, route37, route38, route39, route40, route41]);
const workspaceLayout = skeleton.workspaceLayout.addChildren([
  route12, route13, route14, route15, route16, route17, route18, route21, route22, route30,
  projectLayout,
  workspaceSettings,
]);

export const routeTree = skeleton.rootRoute.addChildren([
  route0, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, route32,
  workspaceLayout,
]);

export const router = createRouter({
  routeTree,
  context: {auth: undefined, queryClient: undefined} satisfies RouterContext,
  scrollRestoration: true,
  parseSearch: parseAppSearch,
  stringifySearch: stringifyAppSearch,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
