// GENERATED by @shipfox/client-shell/vite. Do not edit.
// biome-ignore-all format: generated code has stable, reviewable output.
// biome-ignore-all assist/source/organizeImports: generated imports follow route order.
import {createRoute, createRouter} from '@tanstack/react-router';
import {buildAnchorSkeleton, isRouteImpl, type RouteImpl, type RouterContext} from '@shipfox/client-shell/runtime';
import * as route0Module from "@shipfox/client-auth/routes/index";
import * as route1Module from "@shipfox/client-auth/routes/login";
import * as route2Module from "@shipfox/client-auth/routes/logout";
import * as route3Module from "@shipfox/client-auth/routes/reset";
import * as route4Module from "@shipfox/client-auth/routes/signup";
import * as route5Module from "@shipfox/client-auth/routes/workspace-onboarding";
import * as route6Module from "@shipfox/client-invitations/routes/accept";
import * as route7Module from "@shipfox/client-integrations/routes/github-callback";
import * as route8Module from "@shipfox/client-integrations/routes/linear-callback";
import * as route9Module from "@shipfox/client-integrations/routes/sentry-callback";
import * as route10Module from "@shipfox/client-integrations/routes/slack-callback";
import * as route11Module from "@shipfox/client-integrations/routes/integrations";
import * as route12Module from "@shipfox/client-integrations/routes/gitea";
import * as route13Module from "@shipfox/client-integrations/routes/github";
import * as route14Module from "@shipfox/client-integrations/routes/linear";
import * as route15Module from "@shipfox/client-integrations/routes/sentry";
import * as route16Module from "@shipfox/client-integrations/routes/slack";
import * as route17Module from "@shipfox/client-projects/routes/home";
import * as route18Module from "@shipfox/client-projects/routes/create-project";
import * as route19Module from "@shipfox/client-projects/routes/project-index";
import * as route20Module from "@shipfox/client-projects/routes/workflows";
import * as route21Module from "@shipfox/client-workflows/routes/runs";
import * as route22Module from "@shipfox/client-workflows/routes/run-detail";
import * as route23Module from "@shipfox/client-agent/routes/model-provider";
import * as route24Module from "@shipfox/client-workspace-settings/routes/index";
import * as route25Module from "@shipfox/client-workspace-settings/routes/members";
import * as route26Module from "@shipfox/client-workspace-settings/routes/runners";
import * as route27Module from "@shipfox/client-workspace-settings/routes/provisioners";
import * as route28Module from "@shipfox/client-workspace-settings/routes/agents";
import * as route29Module from "@shipfox/client-workspace-settings/routes/secrets";
import * as route30Module from "@shipfox/client-workspace-settings/routes/variables";
import * as route31Module from "@shipfox/client-workspace-settings/routes/integrations";
import * as route32Module from "@shipfox/client-workspace-settings/routes/events";

function routeOptions<T extends RouteImpl>(routeImpl: T, impl: string, path: string): T['options'] {
  if (!isRouteImpl(routeImpl)) {
    throw new TypeError(`Route implementation "${impl}" for "${path}" must export default defineRoute(...).`);
  }
  return routeImpl.options;
}

const skeleton = buildAnchorSkeleton({
  navigation: [
    {
      "id": "nav.projects",
      "scope": "workspace",
      "label": "Projects",
      "to": "/workspaces/$wid",
      "exact": true,
      "order": 100
    },
    {
      "id": "nav.runs",
      "scope": "project",
      "label": "Runs",
      "to": "/workspaces/$wid/projects/$pid/runs",
      "order": 100
    },
    {
      "id": "nav.workflows",
      "scope": "project",
      "label": "Workflows",
      "to": "/workspaces/$wid/projects/$pid/workflows",
      "order": 200
    },
    {
      "id": "nav.settings",
      "scope": "workspace",
      "label": "Settings",
      "to": "/workspaces/$wid/settings",
      "order": 200
    }
  ],
  settingsSections: [
    {
      "id": "settings.members",
      "pathSegment": "members",
      "label": "Members",
      "icon": "userLine",
      "order": 100
    },
    {
      "id": "settings.runners",
      "pathSegment": "runners",
      "label": "Runners",
      "icon": "settings3Line",
      "order": 200
    },
    {
      "id": "settings.provisioners",
      "pathSegment": "provisioners",
      "label": "Runner provisioners",
      "icon": "serverLine",
      "order": 300
    },
    {
      "id": "settings.agents",
      "pathSegment": "agents",
      "label": "Agents",
      "icon": "robot2Line",
      "order": 400
    },
    {
      "id": "settings.secrets",
      "pathSegment": "secrets",
      "label": "Secrets",
      "icon": "keyLine",
      "order": 500
    },
    {
      "id": "settings.variables",
      "pathSegment": "variables",
      "label": "Variables",
      "icon": "bracesLine",
      "order": 600
    },
    {
      "id": "settings.integrations",
      "pathSegment": "integrations",
      "label": "Integrations",
      "icon": "plugLine",
      "order": 700
    },
    {
      "id": "settings.events",
      "pathSegment": "events",
      "label": "Events",
      "icon": "pulseLine",
      "order": 800
    }
  ],
});

const route0 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/",
  ...routeOptions(route0Module.default, "@shipfox/client-auth/routes/index", "/"),
});

const route1 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/login",
  ...routeOptions(route1Module.default, "@shipfox/client-auth/routes/login", "/auth/login"),
});

const route2 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/logout",
  ...routeOptions(route2Module.default, "@shipfox/client-auth/routes/logout", "/auth/logout"),
});

const route3 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/reset",
  ...routeOptions(route3Module.default, "@shipfox/client-auth/routes/reset", "/auth/reset"),
});

const route4 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/auth/signup",
  ...routeOptions(route4Module.default, "@shipfox/client-auth/routes/signup", "/auth/signup"),
});

const route5 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/setup/workspaces/new",
  ...routeOptions(route5Module.default, "@shipfox/client-auth/routes/workspace-onboarding", "/setup/workspaces/new"),
});

const route6 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/invitations/accept",
  ...routeOptions(route6Module.default, "@shipfox/client-invitations/routes/accept", "/invitations/accept"),
});

const route7 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/github/callback",
  ...routeOptions(route7Module.default, "@shipfox/client-integrations/routes/github-callback", "/integrations/github/callback"),
});

const route8 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/linear/callback",
  ...routeOptions(route8Module.default, "@shipfox/client-integrations/routes/linear-callback", "/integrations/linear/callback"),
});

const route9 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/sentry/callback",
  ...routeOptions(route9Module.default, "@shipfox/client-integrations/routes/sentry-callback", "/integrations/sentry/callback"),
});

const route10 = createRoute({
  getParentRoute: () => skeleton.rootRoute,
  path: "/integrations/slack/callback",
  ...routeOptions(route10Module.default, "@shipfox/client-integrations/routes/slack-callback", "/integrations/slack/callback"),
});

const route11 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations",
  ...routeOptions(route11Module.default, "@shipfox/client-integrations/routes/integrations", "/workspaces/$wid/integrations"),
});

const route12 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/gitea",
  ...routeOptions(route12Module.default, "@shipfox/client-integrations/routes/gitea", "/workspaces/$wid/integrations/gitea"),
});

const route13 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/github",
  ...routeOptions(route13Module.default, "@shipfox/client-integrations/routes/github", "/workspaces/$wid/integrations/github"),
});

const route14 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/linear",
  ...routeOptions(route14Module.default, "@shipfox/client-integrations/routes/linear", "/workspaces/$wid/integrations/linear"),
});

const route15 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/sentry",
  ...routeOptions(route15Module.default, "@shipfox/client-integrations/routes/sentry", "/workspaces/$wid/integrations/sentry"),
});

const route16 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/integrations/slack",
  ...routeOptions(route16Module.default, "@shipfox/client-integrations/routes/slack", "/workspaces/$wid/integrations/slack"),
});

const route17 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/",
  ...routeOptions(route17Module.default, "@shipfox/client-projects/routes/home", "/workspaces/$wid"),
});

const route18 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/projects/new",
  ...routeOptions(route18Module.default, "@shipfox/client-projects/routes/create-project", "/workspaces/$wid/projects/new"),
});

const route19 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/",
  ...routeOptions(route19Module.default, "@shipfox/client-projects/routes/project-index", "/workspaces/$wid/projects/$pid"),
});

const route20 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/workflows",
  ...routeOptions(route20Module.default, "@shipfox/client-projects/routes/workflows", "/workspaces/$wid/projects/$pid/workflows"),
});

const route21 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/runs",
  ...routeOptions(route21Module.default, "@shipfox/client-workflows/routes/runs", "/workspaces/$wid/projects/$pid/runs"),
});

const route22 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/runs/$workflowRunId",
  ...routeOptions(route22Module.default, "@shipfox/client-workflows/routes/run-detail", "/workspaces/$wid/projects/$pid/runs/$workflowRunId"),
});

const route23 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/model-provider",
  ...routeOptions(route23Module.default, "@shipfox/client-agent/routes/model-provider", "/workspaces/$wid/model-provider"),
});

const route24 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/",
  ...routeOptions(route24Module.default, "@shipfox/client-workspace-settings/routes/index", "/workspaces/$wid/settings"),
});

const route25 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/members",
  ...routeOptions(route25Module.default, "@shipfox/client-workspace-settings/routes/members", "/workspaces/$wid/settings/members"),
});

const route26 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/runners",
  ...routeOptions(route26Module.default, "@shipfox/client-workspace-settings/routes/runners", "/workspaces/$wid/settings/runners"),
});

const route27 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/provisioners",
  ...routeOptions(route27Module.default, "@shipfox/client-workspace-settings/routes/provisioners", "/workspaces/$wid/settings/provisioners"),
});

const route28 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/agents",
  ...routeOptions(route28Module.default, "@shipfox/client-workspace-settings/routes/agents", "/workspaces/$wid/settings/agents"),
});

const route29 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/secrets",
  ...routeOptions(route29Module.default, "@shipfox/client-workspace-settings/routes/secrets", "/workspaces/$wid/settings/secrets"),
});

const route30 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/variables",
  ...routeOptions(route30Module.default, "@shipfox/client-workspace-settings/routes/variables", "/workspaces/$wid/settings/variables"),
});

const route31 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/integrations",
  ...routeOptions(route31Module.default, "@shipfox/client-workspace-settings/routes/integrations", "/workspaces/$wid/settings/integrations"),
});

const route32 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/events",
  ...routeOptions(route32Module.default, "@shipfox/client-workspace-settings/routes/events", "/workspaces/$wid/settings/events"),
});

const projectLayout = skeleton.projectLayout.addChildren([route19, route20, route21, route22]);
const workspaceSettings = skeleton.workspaceSettings.addChildren([route24, route25, route26, route27, route28, route29, route30, route31, route32]);
const workspaceLayout = skeleton.workspaceLayout.addChildren([
  route11, route12, route13, route14, route15, route16, route17, route18, route23,
  projectLayout,
  workspaceSettings,
]);

export const routeTree = skeleton.rootRoute.addChildren([
  route0, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10,
  workspaceLayout,
]);

export const router = createRouter({
  routeTree,
  context: {auth: undefined, queryClient: undefined} satisfies RouterContext,
  scrollRestoration: true,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
