import {surfaceWorkflowDocumentCueSchema} from '#core/surface/surface-workflow-document-cue.js';

export type FormalizationDocStatus = 'draft' | 'generated' | 'normative' | 'deferred';

export type FormalizationDocSection = {
  readonly title: string;
  readonly body: readonly string[];
};

export type FormalizationDoc = {
  readonly fileName: string;
  readonly title: string;
  readonly status: FormalizationDocStatus;
  readonly sourceOfTruth: string;
  readonly purpose: readonly string[];
  readonly normativeModel: readonly string[];
  readonly generatedLines: readonly string[];
  readonly examples: readonly string[];
  readonly addingOrChanging: readonly string[];
  readonly deferredWork: readonly string[];
  readonly extraSections?: readonly FormalizationDocSection[];
};

export const generatedSectionMarker =
  '<!-- generated by libs/api/workflow-language/scripts/generate-formalization-docs.ts; do not edit generated sections directly -->';

export const generatedSectionStart = '<!-- generated:start -->';
export const generatedSectionEnd = '<!-- generated:end -->';

export const formalizationDocs: readonly FormalizationDoc[] = [
  {
    fileName: '000-requirements-ledger.md',
    title: '000 Requirements Ledger',
    status: 'normative',
    sourceOfTruth: 'docs/formalizing-shipfox-runtime/000-requirements-ledger.md',
    purpose: [
      'Track the PR1 runtime-formalization requirements, whether each one is implemented, and where the implementation or deferral is documented.',
      'This document is the repo-owned ledger for reviewers. It does not depend on temporary planning artifacts.',
    ],
    normativeModel: [
      '- Preserve the current YAML authoring surface for PR1.',
      '- Introduce a shared workflow-language package below feature packages.',
      '- Derive runtime semantics from a normalized IR at run creation.',
      '- Formalize job-level runtime behavior before step-level semantics.',
      '- Commit generated documentation whenever code-derived sections change.',
    ],
    generatedLines: [
      '- `@shipfox/api-workflow-language` owns formalization helpers and generated documentation sections.',
      '- PR1 documentation is written under `docs/formalizing-shipfox-runtime/`.',
      '- Generated docs are checked by `libs/api/workflow-language/src/docs/formalization-doc-model.test.ts`.',
    ],
    examples: [
      'A requirement can be marked included when the matching code, tests, and generated docs are committed in the same slice.',
    ],
    addingOrChanging: [
      'Add a requirement row before implementing a new formalized concept, then update its status in the commit that lands the code.',
    ],
    deferredWork: ['- See the PR1 Requirement Status table for included and deferred work.'],
    extraSections: [
      {
        title: 'PR1 Requirement Status',
        body: [
          '| Requirement | PR1 status | Primary docs | Primary code |',
          '| --- | --- | --- | --- |',
          '| Preserve current YAML surface and public wire names | Included | `001-yaml-surface.md` | `libs/api/definitions-dto`, `libs/api/definitions` |',
          '| Rename TypeScript surface concepts away from `WorkflowSpec` | Included | `001-yaml-surface.md` | `libs/api/workflow-language/src/core/surface/` |',
          '| Provide a CUE formalization artifact without accepting CUE input | Included | `002-cue-schema.md` | `libs/api/workflow-language/src/core/surface/surface-workflow-document-cue.ts` |',
          '| Normalize YAML surface documents into `WorkflowIR` | Included | `004-core-ir.md` | `libs/api/workflow-language/src/core/ir/` |',
          '| Reuse static semantics for validation and run creation | Included | `005-static-semantics.md` | `libs/api/workflow-language/src/core/static-semantics/`, `libs/api/definitions`, `libs/api/workflows` |',
          '| Create workflow runs from normalized IR | Included | `004-core-ir.md`, `005-static-semantics.md` | `libs/api/workflows/src/core/run-workflow.ts`, `libs/api/workflows/src/db/workflow-runs.ts` |',
          '| Formalize job-level runtime transitions with golden traces | Included | `006-runtime-transitions.md` | `libs/api/workflows/src/core/runtime/` |',
          '| Delegate Temporal scheduling decisions to the runtime kernel | Included | `007-durable-shell.md` | `libs/api/workflows/src/temporal/workflows/run-orchestration.ts` |',
          '| Define process for new formalized concepts | Included | `008-adding-new-concepts.md` | `libs/api/workflow-language/src/docs/formalization-doc-model.ts` |',
          '| Document generated-doc workflow | Included | `009-doc-generation.md` | `libs/api/workflow-language/scripts/generate-formalization-docs.ts` |',
          '| Public wire rename from `definition` to `document` | Deferred | `001-yaml-surface.md` | deferred |',
          '| CUE as an accepted authoring surface | Deferred | `002-cue-schema.md` | deferred |',
          '| Custom expression parser and `gate.success_if` evaluation | Deferred | `003-expression-language.md` | deferred |',
          '| Cached WorkflowIR persistence | Deferred | `004-core-ir.md` | deferred |',
          '| Runtime state snapshots | Deferred | `006-runtime-transitions.md`, `007-durable-shell.md` | deferred |',
          '| Step-level runtime transitions | Deferred | `006-runtime-transitions.md` | deferred |',
          '| Pipelined child workflow scheduling across sibling branches | Deferred | `007-durable-shell.md` | deferred |',
        ],
      },
    ],
  },
  {
    fileName: '001-yaml-surface.md',
    title: '001 YAML Surface',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/surface/surface-workflow-document.ts',
    purpose: [
      'Describe the author-facing YAML document accepted by PR1.',
      'This document tracks compatibility constraints for the surface schema owned by workflow-language.',
    ],
    normativeModel: [
      '- A workflow document has a required non-empty `name`.',
      '- `jobs` is a map keyed by job name.',
      '- `triggers` remains an optional map keyed by trigger name.',
      '- `runner`, job `runner`, and job `needs` accept either a string or a string array.',
    ],
    generatedLines: [
      '- Canonical DTO surface schema: `surfaceWorkflowDocumentSchema`.',
      '- Canonical DTO surface type: `SurfaceWorkflowDocumentDto`.',
      '- Canonical YAML parser: `parseYamlSurfaceWorkflowDocument`.',
      '- Surface compatibility mode: required workflow name, trigger map, HTTP `definition` field, SQL `definition` column.',
      '- Validate-route compatibility mode: response field `spec` and error code `invalid-definition-spec` remain stable.',
    ],
    examples: ['A minimal document declares `name` and one job with at least one `run` step.'],
    addingOrChanging: [
      'Update the Zod schema, CUE formalization artifact, examples, compatibility tests, and generated docs together.',
    ],
    deferredWork: [
      '- Optional workflow names.',
      '- Trigger list authoring shape.',
      '- Additional surface languages.',
      '- Public wire rename from `definition` to `document`.',
    ],
  },
  {
    fileName: '002-cue-schema.md',
    title: '002 CUE Schema',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/surface/surface-workflow-document-cue.ts',
    purpose: [
      'Define how PR1 uses CUE as a formalization artifact for the YAML-produced surface document shape.',
      'PR1 does not accept CUE files as workflow authoring input.',
    ],
    normativeModel: [
      '- The CUE artifact formalizes the post-YAML object shape.',
      '- Runtime and HTTP behavior remain driven by the current YAML ingestion path.',
      '- CUE tooling is optional until a dedicated toolchain decision is made.',
    ],
    generatedLines: [
      '- CUE authoring input support: deferred.',
      '- CUE schema execution in CI: deferred unless the PR adds the `cue` CLI deliberately.',
      `\`\`\`cue\n${surfaceWorkflowDocumentCueSchema.trim()}\n\`\`\``,
    ],
    examples: [
      'Use CUE snippets in this document to explain shape constraints, not as accepted input examples.',
    ],
    addingOrChanging: [
      'When the YAML shape changes, update the CUE artifact in the same commit and add a drift test if the artifact is code-derived.',
    ],
    deferredWork: ['- CUE as a first-class surface language.'],
  },
  {
    fileName: '003-expression-language.md',
    title: '003 Expression Language',
    status: 'deferred',
    sourceOfTruth: 'libs/api/workflow-language/src/core/ir/expression-ir.ts',
    purpose: ['Document expression-language scope and intentionally unsupported behavior for PR1.'],
    normativeModel: [
      '- PR1 must not pass raw custom gate expressions into runtime semantics.',
      '- Default gate policy may be represented as a typed built-in concept.',
      '- Runner-reported command facts must exist before runtime expression evaluation can be meaningful.',
      '- Any future expression string must have a parser, AST, static diagnostics, evaluator, and tests before being accepted by runtime semantics.',
    ],
    generatedLines: [
      '- Expression parser implementation: deferred in PR1.',
      '- PR1 IR acceptance policy: typed `default_run_exit_code` with expression kind `output.exit_code == 0`.',
      '- PR1 runtime evaluation: job completion status is reported by the runner/job orchestration path, not by a custom expression evaluator.',
    ],
    examples: [
      'A default success policy can be named as a built-in rather than represented by a raw string.',
      'A future `gate.success_if: output.exit_code == 0 && tests.failed == 0` field must not be forwarded as an opaque string; it needs typed parsing and diagnostics first.',
    ],
    addingOrChanging: [
      'Add grammar, AST, parser tests, docs, and static diagnostics before accepting any new expression string.',
      'Update IR normalization so expression-bearing fields become typed expression nodes rather than raw strings.',
      'Update runtime traces only after the evaluator can consume runner facts deterministically.',
    ],
    deferredWork: [
      '- Custom `gate.success_if` parsing.',
      '- Expression typechecking over runner facts.',
      '- Runtime expression evaluator.',
      '- Runner DTOs for structured command facts.',
    ],
  },
  {
    fileName: '004-core-ir.md',
    title: '004 Core IR',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/ir/workflow-ir.ts',
    purpose: ['Describe the normalized semantic model that workflow execution consumes.'],
    normativeModel: [
      '- WorkflowIR is derived at run creation by `@shipfox/api-workflows`.',
      '- PR1 does not cache WorkflowIR in Postgres.',
      '- Trigger maps normalize to ordered IR trigger lists.',
      '- Job dependencies normalize to explicit dependency edges.',
      '- Run steps normalize to explicit step IDs and typed default acceptance policies.',
    ],
    generatedLines: [
      '- WorkflowIR type owner: `libs/api/workflow-language/src/core/ir/workflow-ir.ts`.',
      '- Normalizer owner: `libs/api/workflow-language/src/core/ir/normalize-surface-document.ts`.',
      '- ID helper owner: `libs/api/workflow-language/src/core/ir/ids.ts`.',
      '- Expression/default-gate owner: `libs/api/workflow-language/src/core/ir/expression-ir.ts`.',
      '- Trigger maps are sorted by trigger name and normalized to `TriggerIR[]`.',
      '- Job maps are sorted by job name and normalized to `JobIR[]` for deterministic IDs.',
      '- `JobIR.sourceName` preserves the surface map key for author-facing diagnostics.',
      '- `JobIR.position` preserves the authored job order for persistence and UI ordering.',
      '- Job and trigger IDs are slugified from surface map keys with numeric suffixes for collisions.',
      '- Step IDs use `<job-id>.<slugified step name or run command>` with numeric suffixes for collisions.',
      '- The only PR1 acceptance policy in IR is `default_run_exit_code` with a typed `exit_code == 0` expression.',
    ],
    examples: [
      'A job dependency map such as `deploy.needs: [build, test]` becomes explicit edges `build -> deploy` and `test -> deploy`.',
      'Surface map keys `build main` and `build_main` normalize to job IDs `build-main` and `build-main-2`.',
      'Two anonymous `run: pnpm install` steps in job `build` normalize to `build.pnpm-install` and `build.pnpm-install-2`.',
    ],
    addingOrChanging: [
      'Update IR types, normalizer tests, static semantics, runtime docs, and generated docs when adding IR concepts.',
    ],
    deferredWork: [
      '- Cached WorkflowIR persistence.',
      '- Custom `gate.success_if` parsing and runtime evaluation.',
    ],
  },
  {
    fileName: '005-static-semantics.md',
    title: '005 Static Semantics',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/static-semantics/diagnostic.ts',
    purpose: ['Document reusable validation rules over WorkflowIR.'],
    normativeModel: [
      '- Static diagnostics use stable IDs.',
      '- Definitions parse-time validation uses shared WorkflowIR static checks.',
      '- Run creation uses the same static checks before persisting jobs and steps.',
    ],
    generatedLines: [
      '- Diagnostic registry owner: `libs/api/workflow-language/src/core/static-semantics/diagnostic.ts`.',
      '- Static check owner: `libs/api/workflow-language/src/core/static-semantics/validate-workflow-ir.ts`.',
      '- `SS001_UNKNOWN_JOB_DEPENDENCY`: dependency edge references a missing job.',
      '- `SS002_SELF_JOB_DEPENDENCY`: dependency edge points from a job to itself.',
      '- `SS003_CYCLIC_JOB_DEPENDENCY`: dependency graph contains a cycle.',
      '- `SS004_UNKNOWN_DEPENDENT_JOB`: dependency edge targets a missing job.',
      '- Reference diagnostics are reported before cycle diagnostics because cycle analysis requires resolvable edge endpoints.',
      '- Static diagnostics use `JobIR.sourceName` when reporting author-facing job names and paths.',
    ],
    examples: [
      'A surface `needs: ghost` entry normalizes to an unresolved IR edge and returns `SS001_UNKNOWN_JOB_DEPENDENCY`.',
      'A malformed IR edge targeting a missing job returns `SS004_UNKNOWN_DEPENDENT_JOB`.',
      'A cycle such as `a -> b -> c -> a` returns `SS003_CYCLIC_JOB_DEPENDENCY`.',
    ],
    addingOrChanging: [
      'Add diagnostic IDs, tests, docs, and call sites for each new semantic rule.',
    ],
    deferredWork: ['- Rich runner fact validation.'],
  },
  {
    fileName: '006-runtime-transitions.md',
    title: '006 Runtime Transitions',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflows/src/core/runtime/',
    purpose: ['Document the pure job-level runtime transition system.'],
    normativeModel: [
      '- PR1 runtime formalization is job-level.',
      '- Runtime transition logic should be pure and replayable.',
      '- Temporal remains the durable shell around semantic decisions.',
      '- Runtime input is expected to be normalized and statically validated before transition replay.',
    ],
    generatedLines: [
      '- Runtime state owner: `libs/api/workflows/src/core/runtime/runtime-state.ts`.',
      '- Runtime event owner: `libs/api/workflows/src/core/runtime/runtime-event.ts`.',
      '- Runtime command owner: `libs/api/workflows/src/core/runtime/runtime-command.ts`.',
      '- Runtime transition owner: `libs/api/workflows/src/core/runtime/transition.ts`.',
      '- Golden traces live under `libs/api/workflows/src/core/runtime/traces/`.',
      '- Initial PR1 runtime events: `run_started`, `job_completed`.',
      '- Initial PR1 runtime commands: `start_job`, `cancel_job`, `complete_run`.',
      '- Events that cannot advance a replay, such as duplicate completions or terminal-run events, are no-ops.',
      '- If no pending job can start and no job is running, the kernel cancels pending jobs and fails the run.',
      '- Wall-clock timeout remains a Temporal durable-shell concern.',
    ],
    examples: ['A failed job cancels dependent jobs according to job-level dependency rules.'],
    addingOrChanging: [
      'Add transition metadata, golden traces, durable-shell updates, and docs in the same commit sequence.',
    ],
    deferredWork: ['- Step-level runtime transitions.', '- Runtime state snapshots.'],
  },
  {
    fileName: '007-durable-shell.md',
    title: '007 Durable Shell',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflows/src/temporal/',
    purpose: [
      'Describe how Temporal and persistence adapt pure runtime commands to durable execution.',
    ],
    normativeModel: [
      '- Temporal is responsible for durability, timers, activities, and signal interpretation.',
      '- Runtime semantics belong in the pure kernel.',
      '- Temporal interprets runtime commands through child workflows and activities.',
    ],
    generatedLines: [
      '- Durable shell owner: `libs/api/workflows/src/temporal/workflows/run-orchestration.ts`.',
      '- Job execution shell owner: `libs/api/workflows/src/temporal/workflows/job-orchestration.ts`.',
      '- Activity adapter owner: `libs/api/workflows/src/temporal/activities/orchestration-activities.ts`.',
      '- `start_job` maps to a child `jobOrchestration` workflow.',
      '- `cancel_job` maps to durable job status cancellation.',
      '- `complete_run` maps to durable workflow-run status completion.',
      '- Job timeout remains in `jobOrchestration` and timeout activities.',
      '- Current run orchestration awaits each emitted `start_job` batch as a batch before processing downstream commands.',
    ],
    examples: [
      'Temporal can keep timeout handling while delegating readiness decisions to the kernel.',
    ],
    addingOrChanging: [
      'Update shell adapters and tests only when persistence, Temporal, outbox, runner, or trigger behavior changes.',
    ],
    deferredWork: [
      '- Runtime state snapshots.',
      '- Pipelined child workflow scheduling across sibling branches.',
    ],
  },
  {
    fileName: '008-adding-new-concepts.md',
    title: '008 Adding New Concepts',
    status: 'normative',
    sourceOfTruth: 'docs/formalizing-shipfox-runtime/008-adding-new-concepts.md',
    purpose: ['Define the process for adding or changing formalized workflow concepts.'],
    normativeModel: [
      '1. Add or update the requirement in `000-requirements-ledger.md`.',
      '2. Classify the concept as surface-only, semantic/static, runtime-stateful, or adapter-only.',
      '3. Update the YAML surface schema if the authoring shape changes.',
      '4. Update the CUE formalization artifact if the surface document shape changes.',
      '5. Update expression language grammar/docs if the concept introduces expression strings or new expression scope.',
      '6. Normalize the concept into WorkflowIR, or document why it normalizes away.',
      '7. Add or update static semantic checks.',
      '8. Add runtime transition rules only if runtime behavior changes.',
      '9. Update durable shell adapters only if persistence, Temporal, outbox, runner, or triggers behavior changes.',
      '10. Add generated docs and examples.',
      '11. Add tests at the right layer.',
      '12. Track intentionally deferred follow-up work.',
    ],
    examples: [
      'A new authoring field starts in the ledger, then updates surface validation, CUE, IR normalization, diagnostics, docs, and tests as needed.',
    ],
    addingOrChanging: [
      'Change this process only when a PR demonstrates that the current sequence misses a required formalization layer.',
    ],
    generatedLines: [
      '- Formalized concept process version: PR1 job-level runtime formalization.',
      '- New docs should be added to `formalizationDocs` so generation and committed-output tests cover them.',
      '- Runtime-changing concepts require golden traces before durable-shell wiring.',
    ],
    deferredWork: [
      '- Repo-local deferred task index if per-document deferred sections become too fragmented after PR1.',
    ],
    extraSections: [
      {
        title: 'Concept Change Template',
        body: [
          'Use this condensed view of the model above when adding a new workflow concept:',
          '1. Requirement: add or update a row in `000-requirements-ledger.md`.',
          '2. Classification: choose surface-only, semantic/static, runtime-stateful, adapter-only, or a combination.',
          '3. Surface: update Zod schemas, YAML parser tests, examples, and CUE artifact when authoring shape changes.',
          '4. IR: normalize the concept into `WorkflowIR`, or document why it is intentionally surface-only.',
          '5. Static semantics: add diagnostic IDs and tests for invalid cross-field or graph states.',
          '6. Runtime: add events, commands, state fields, transition tests, and golden traces when behavior changes.',
          '7. Durable shell: update Temporal, persistence, outbox, runner, or trigger adapters only for side effects the pure model cannot own.',
          '8. Docs: update `formalization-doc-model.ts`, regenerate docs, and commit generated Markdown.',
          '9. Tests: run the smallest affected package graph first, then broader affected checks before commit.',
          '10. Deferrals: document deliberately postponed work in the relevant document deferred section.',
        ],
      },
    ],
  },
  {
    fileName: '009-doc-generation.md',
    title: '009 Doc Generation',
    status: 'normative',
    sourceOfTruth: 'libs/api/workflow-language/scripts/generate-formalization-docs.ts',
    purpose: ['Explain how generated formalization documentation is produced and reviewed.'],
    normativeModel: [
      '- Generated sections are delimited by generated markers.',
      '- The generator must be deterministic.',
      '- Generated docs are committed with the code that changes them.',
      '- Do not include wall-clock timestamps in generated output.',
    ],
    generatedLines: [
      '- Package generator command: `pnpm --filter=@shipfox/api-workflow-language generate:docs`.',
      '- Turbo generator command: `turbo generate:docs --filter=@shipfox/api-workflow-language`.',
      '- Generator script owner: `libs/api/workflow-language/scripts/generate-formalization-docs.ts`.',
      '- Generated content model owner: `libs/api/workflow-language/src/docs/formalization-doc-model.ts`.',
      '- Committed-output test owner: `libs/api/workflow-language/src/docs/formalization-doc-model.test.ts`.',
      '- Generated section marker is exported as `generatedSectionMarker`.',
    ],
    examples: [
      'Run the generator twice without code changes; the second run should produce no diff.',
    ],
    addingOrChanging: [
      'Update the doc model test whenever generator structure or generated section behavior changes.',
      'Do not hand-edit generated sections; update `formalization-doc-model.ts` and rerun the generator.',
      'When code-derived facts change, commit the generated Markdown in the same commit as the code.',
    ],
    deferredWork: [
      '- Broader generated coverage as IR, diagnostics, and runtime metadata are introduced.',
    ],
    extraSections: [
      {
        title: 'Review Checklist',
        body: [
          '- Run `turbo generate:docs --filter=@shipfox/api-workflow-language` after changing the doc model or generated facts.',
          '- Run `turbo test --filter=@shipfox/api-workflow-language...` so the committed-output test verifies generated docs.',
          '- Confirm a second generator run produces no diff.',
          '- Keep generated output free of timestamps, random ordering, environment-specific paths, and temporary planning references.',
        ],
      },
    ],
  },
];

function renderBlock(lines: readonly string[]): string {
  return lines.length === 0 ? 'None.' : lines.join('\n\n');
}

export function renderFormalizationDoc(doc: FormalizationDoc): string {
  const sections = [
    `# ${doc.title}`,
    `Status: ${doc.status}\nSource of truth: ${doc.sourceOfTruth}`,
    `## Purpose\n\n${renderBlock(doc.purpose)}`,
    `## Normative Model\n\n${renderBlock(doc.normativeModel)}\n\n${generatedSectionMarker}\n${generatedSectionStart}\n${renderBlock(doc.generatedLines)}\n${generatedSectionEnd}`,
    `## Examples\n\n${renderBlock(doc.examples)}`,
    `## Adding Or Changing This Concept\n\n${renderBlock(doc.addingOrChanging)}`,
    `## Deferred Work\n\n${renderBlock(doc.deferredWork)}`,
    ...(doc.extraSections?.map(
      (section) => `## ${section.title}\n\n${renderBlock(section.body)}`,
    ) ?? []),
  ];

  return `${sections.join('\n\n')}\n`;
}

export function renderFormalizationDocs(
  docs: readonly FormalizationDoc[] = formalizationDocs,
): ReadonlyMap<string, string> {
  return new Map(docs.map((doc) => [doc.fileName, renderFormalizationDoc(doc)]));
}
