import {surfaceWorkflowDocumentCueSchema} from '#core/surface/surface-workflow-document-cue.js';

export type FormalizationDocStatus = 'draft' | 'generated' | 'normative' | 'deferred';

export type FormalizationDocSection = {
  readonly title: string;
  readonly body: readonly string[];
};

export type FormalizationDoc = {
  readonly fileName: string;
  readonly title: string;
  readonly status: FormalizationDocStatus;
  readonly sourceOfTruth: string;
  readonly purpose: readonly string[];
  readonly normativeModel: readonly string[];
  readonly generatedLines: readonly string[];
  readonly examples: readonly string[];
  readonly addingOrChanging: readonly string[];
  readonly deferredWork: readonly string[];
  readonly extraSections?: readonly FormalizationDocSection[];
};

export const generatedSectionMarker =
  '<!-- generated by libs/api/workflow-language/scripts/generate-formalization-docs.ts; do not edit generated sections directly -->';

export const generatedSectionStart = '<!-- generated:start -->';
export const generatedSectionEnd = '<!-- generated:end -->';

export const formalizationDocs: readonly FormalizationDoc[] = [
  {
    fileName: '000-requirements-ledger.md',
    title: '000 Requirements Ledger',
    status: 'draft',
    sourceOfTruth: 'docs/formalizing-shipfox-runtime/000-requirements-ledger.md',
    purpose: [
      'Track the PR1 runtime-formalization requirements, whether each one is implemented, and where the implementation or deferral is documented.',
      'This document is the repo-owned ledger for reviewers. It does not depend on temporary planning artifacts.',
    ],
    normativeModel: [
      '- Preserve the current YAML authoring surface for PR1.',
      '- Introduce a shared workflow-language package below feature packages.',
      '- Derive runtime semantics from a normalized IR at run creation.',
      '- Formalize job-level runtime behavior before step-level semantics.',
      '- Commit generated documentation whenever code-derived sections change.',
    ],
    generatedLines: [
      '- `@shipfox/api-workflow-language` owns formalization helpers and generated documentation sections.',
      '- PR1 documentation is written under `docs/formalizing-shipfox-runtime/`.',
    ],
    examples: [
      'A requirement can be marked included when the matching code, tests, and generated docs are committed in the same slice.',
    ],
    addingOrChanging: [
      'Add a requirement row before implementing a new formalized concept, then update its status in the commit that lands the code.',
    ],
    deferredWork: [
      '- Public wire rename from `definition` to `document`.',
      '- CUE as an authoring surface language.',
      '- Step-level runtime transition semantics.',
    ],
  },
  {
    fileName: '001-yaml-surface.md',
    title: '001 YAML Surface',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/surface/surface-workflow-document.ts',
    purpose: [
      'Describe the author-facing YAML document accepted by PR1.',
      'This document tracks compatibility constraints for the surface schema owned by workflow-language.',
    ],
    normativeModel: [
      '- A workflow document has a required non-empty `name`.',
      '- `jobs` is a map keyed by job name.',
      '- `triggers` remains an optional map keyed by trigger name.',
      '- `runner`, job `runner`, and job `needs` accept either a string or a string array.',
    ],
    generatedLines: [
      '- Canonical DTO surface schema: `surfaceWorkflowDocumentSchema`.',
      '- Canonical DTO surface type: `SurfaceWorkflowDocumentDto`.',
      '- Canonical YAML parser: `parseYamlSurfaceWorkflowDocument`.',
      '- Surface compatibility mode: required workflow name, trigger map, HTTP `definition` field, SQL `definition` column.',
      '- Validate-route compatibility mode: response field `spec` and error code `invalid-definition-spec` remain stable.',
    ],
    examples: ['A minimal document declares `name` and one job with at least one `run` step.'],
    addingOrChanging: [
      'Update the Zod schema, CUE formalization artifact, examples, compatibility tests, and generated docs together.',
    ],
    deferredWork: [
      '- Optional workflow names.',
      '- Trigger list authoring shape.',
      '- Additional surface languages.',
    ],
  },
  {
    fileName: '002-cue-schema.md',
    title: '002 CUE Schema',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/surface/surface-workflow-document-cue.ts',
    purpose: [
      'Define how PR1 uses CUE as a formalization artifact for the YAML-produced surface document shape.',
      'PR1 does not accept CUE files as workflow authoring input.',
    ],
    normativeModel: [
      '- The CUE artifact formalizes the post-YAML object shape.',
      '- Runtime and HTTP behavior remain driven by the current YAML ingestion path.',
      '- CUE tooling is optional until a dedicated toolchain decision is made.',
    ],
    generatedLines: [
      '- CUE authoring input support: deferred.',
      '- CUE schema execution in CI: deferred unless the PR adds the `cue` CLI deliberately.',
      `\`\`\`cue\n${surfaceWorkflowDocumentCueSchema.trim()}\n\`\`\``,
    ],
    examples: [
      'Use CUE snippets in this document to explain shape constraints, not as accepted input examples.',
    ],
    addingOrChanging: [
      'When the YAML shape changes, update the CUE artifact in the same commit and add a drift test if the artifact is code-derived.',
    ],
    deferredWork: ['- CUE as a first-class surface language.'],
  },
  {
    fileName: '003-expression-language.md',
    title: '003 Expression Language',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/expressions/',
    purpose: ['Document expression-language scope and intentionally unsupported behavior for PR1.'],
    normativeModel: [
      '- PR1 must not pass raw custom gate expressions into runtime semantics.',
      '- Default gate policy may be represented as a typed built-in concept.',
    ],
    generatedLines: ['- Expression parser implementation: not present in scaffold commit.'],
    examples: [
      'A default success policy can be named as a built-in rather than represented by a raw string.',
    ],
    addingOrChanging: [
      'Add grammar, AST, parser tests, docs, and static diagnostics before accepting any new expression string.',
    ],
    deferredWork: ['- Custom `gate.success_if` evaluation.'],
  },
  {
    fileName: '004-core-ir.md',
    title: '004 Core IR',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/ir/workflow-ir.ts',
    purpose: ['Describe the normalized semantic model that workflow execution consumes.'],
    normativeModel: [
      '- WorkflowIR is derived at run creation by `@shipfox/api-workflows`.',
      '- PR1 does not cache WorkflowIR in Postgres.',
      '- Trigger maps normalize to ordered IR trigger lists.',
      '- Job dependencies normalize to explicit dependency edges.',
      '- Run steps normalize to explicit step IDs and typed default acceptance policies.',
    ],
    generatedLines: [
      '- WorkflowIR type owner: `libs/api/workflow-language/src/core/ir/workflow-ir.ts`.',
      '- Normalizer owner: `libs/api/workflow-language/src/core/ir/normalize-surface-document.ts`.',
      '- ID helper owner: `libs/api/workflow-language/src/core/ir/ids.ts`.',
      '- Expression/default-gate owner: `libs/api/workflow-language/src/core/ir/expression-ir.ts`.',
      '- Trigger maps are sorted by trigger name and normalized to `TriggerIR[]`.',
      '- Job maps are sorted by job name and normalized to `JobIR[]` for deterministic IDs.',
      '- `JobIR.sourceName` preserves the surface map key for author-facing diagnostics.',
      '- `JobIR.position` preserves the authored job order for persistence and UI ordering.',
      '- Job and trigger IDs are slugified from surface map keys with numeric suffixes for collisions.',
      '- Step IDs use `<job-id>.<slugified step name or run command>` with numeric suffixes for collisions.',
      '- The only PR1 acceptance policy in IR is `default_run_exit_code` with a typed `exit_code == 0` expression.',
    ],
    examples: [
      'A job dependency map such as `deploy.needs: [build, test]` becomes explicit edges `build -> deploy` and `test -> deploy`.',
      'Surface map keys `build main` and `build_main` normalize to job IDs `build-main` and `build-main-2`.',
      'Two anonymous `run: pnpm install` steps in job `build` normalize to `build.pnpm-install` and `build.pnpm-install-2`.',
    ],
    addingOrChanging: [
      'Update IR types, normalizer tests, static semantics, runtime docs, and generated docs when adding IR concepts.',
    ],
    deferredWork: [
      '- Cached WorkflowIR persistence.',
      '- Custom `gate.success_if` parsing and runtime evaluation.',
    ],
  },
  {
    fileName: '005-static-semantics.md',
    title: '005 Static Semantics',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflow-language/src/core/static-semantics/diagnostic.ts',
    purpose: ['Document reusable validation rules over WorkflowIR.'],
    normativeModel: [
      '- Static diagnostics use stable IDs.',
      '- Definitions parse-time validation uses shared WorkflowIR static checks.',
      '- Run creation uses the same static checks before persisting jobs and steps.',
    ],
    generatedLines: [
      '- Diagnostic registry owner: `libs/api/workflow-language/src/core/static-semantics/diagnostic.ts`.',
      '- Static check owner: `libs/api/workflow-language/src/core/static-semantics/validate-workflow-ir.ts`.',
      '- `SS001_UNKNOWN_JOB_DEPENDENCY`: dependency edge references a missing job.',
      '- `SS002_SELF_JOB_DEPENDENCY`: dependency edge points from a job to itself.',
      '- `SS003_CYCLIC_JOB_DEPENDENCY`: dependency graph contains a cycle.',
      '- Reference diagnostics are reported before cycle diagnostics because cycle analysis requires resolvable edge endpoints.',
      '- Static diagnostics use `JobIR.sourceName` when reporting author-facing job names and paths.',
    ],
    examples: [
      'A surface `needs: ghost` entry normalizes to an unresolved IR edge and returns `SS001_UNKNOWN_JOB_DEPENDENCY`.',
      'A cycle such as `a -> b -> c -> a` returns `SS003_CYCLIC_JOB_DEPENDENCY`.',
    ],
    addingOrChanging: [
      'Add diagnostic IDs, tests, docs, and call sites for each new semantic rule.',
    ],
    deferredWork: ['- Rich runner fact validation.'],
  },
  {
    fileName: '006-runtime-transitions.md',
    title: '006 Runtime Transitions',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflows/src/core/runtime/',
    purpose: ['Document the pure job-level runtime transition system once introduced.'],
    normativeModel: [
      '- PR1 runtime formalization is job-level.',
      '- Runtime transition logic should be pure and replayable.',
      '- Temporal remains the durable shell around semantic decisions.',
    ],
    generatedLines: ['- Runtime transition kernel: not present in scaffold commit.'],
    examples: ['A failed job cancels dependent jobs according to job-level dependency rules.'],
    addingOrChanging: [
      'Add transition metadata, golden traces, durable-shell updates, and docs in the same commit sequence.',
    ],
    deferredWork: ['- Step-level runtime transitions.', '- Runtime state snapshots.'],
  },
  {
    fileName: '007-durable-shell.md',
    title: '007 Durable Shell',
    status: 'draft',
    sourceOfTruth: 'libs/api/workflows/src/temporal/',
    purpose: [
      'Describe how Temporal and persistence adapt pure runtime commands to durable execution.',
    ],
    normativeModel: [
      '- Temporal is responsible for durability, timers, activities, and signal interpretation.',
      '- Runtime semantics belong in the pure kernel once it exists.',
    ],
    generatedLines: ['- Durable-shell delegation: not present in scaffold commit.'],
    examples: [
      'Temporal can keep timeout handling while delegating readiness decisions to the kernel.',
    ],
    addingOrChanging: [
      'Update shell adapters and tests only when persistence, Temporal, outbox, runner, or trigger behavior changes.',
    ],
    deferredWork: ['- Runtime state snapshots.'],
  },
  {
    fileName: '008-adding-new-concepts.md',
    title: '008 Adding New Concepts',
    status: 'normative',
    sourceOfTruth: 'docs/formalizing-shipfox-runtime/008-adding-new-concepts.md',
    purpose: ['Define the process for adding or changing formalized workflow concepts.'],
    normativeModel: [
      '1. Add or update the requirement in `000-requirements-ledger.md`.',
      '2. Classify the concept as surface-only, semantic/static, runtime-stateful, or adapter-only.',
      '3. Update the YAML surface schema if the authoring shape changes.',
      '4. Update the CUE formalization artifact if the surface document shape changes.',
      '5. Update expression language grammar/docs if the concept introduces expression strings or new expression scope.',
      '6. Normalize the concept into WorkflowIR, or document why it normalizes away.',
      '7. Add or update static semantic checks.',
      '8. Add runtime transition rules only if runtime behavior changes.',
      '9. Update durable shell adapters only if persistence, Temporal, outbox, runner, or triggers behavior changes.',
      '10. Add generated docs and examples.',
      '11. Add tests at the right layer.',
      '12. Track intentionally deferred follow-up work.',
    ],
    generatedLines: ['- Formalized concept process version: PR1 scaffold.'],
    examples: [
      'A new authoring field starts in the ledger, then updates surface validation, CUE, IR normalization, diagnostics, docs, and tests as needed.',
    ],
    addingOrChanging: [
      'Change this process only when a PR demonstrates that the current sequence misses a required formalization layer.',
    ],
    deferredWork: ['- Dedicated repo-local deferred task document if needed after PR1.'],
  },
  {
    fileName: '009-doc-generation.md',
    title: '009 Doc Generation',
    status: 'normative',
    sourceOfTruth: 'libs/api/workflow-language/scripts/generate-formalization-docs.ts',
    purpose: ['Explain how generated formalization documentation is produced and reviewed.'],
    normativeModel: [
      '- Generated sections are delimited by generated markers.',
      '- The generator must be deterministic.',
      '- Generated docs are committed with the code that changes them.',
      '- Do not include wall-clock timestamps in generated output.',
    ],
    generatedLines: [
      '- Generator script: `pnpm --filter=@shipfox/api-workflow-language generate:docs`.',
      '- Generated section marker is owned by `formalization-doc-model.ts`.',
    ],
    examples: [
      'Run the generator twice without code changes; the second run should produce no diff.',
    ],
    addingOrChanging: [
      'Update the doc model test whenever generator structure or generated section behavior changes.',
    ],
    deferredWork: [
      '- Broader generated coverage as IR, diagnostics, and runtime metadata are introduced.',
    ],
  },
];

function renderBlock(lines: readonly string[]): string {
  return lines.length === 0 ? 'None.' : lines.join('\n\n');
}

export function renderFormalizationDoc(doc: FormalizationDoc): string {
  const sections = [
    `# ${doc.title}`,
    `Status: ${doc.status}\nSource of truth: ${doc.sourceOfTruth}`,
    `## Purpose\n\n${renderBlock(doc.purpose)}`,
    `## Normative Model\n\n${renderBlock(doc.normativeModel)}\n\n${generatedSectionMarker}\n${generatedSectionStart}\n${renderBlock(doc.generatedLines)}\n${generatedSectionEnd}`,
    `## Examples\n\n${renderBlock(doc.examples)}`,
    `## Adding Or Changing This Concept\n\n${renderBlock(doc.addingOrChanging)}`,
    `## Deferred Work\n\n${renderBlock(doc.deferredWork)}`,
    ...(doc.extraSections?.map(
      (section) => `## ${section.title}\n\n${renderBlock(section.body)}`,
    ) ?? []),
  ];

  return `${sections.join('\n\n')}\n`;
}

export function renderFormalizationDocs(
  docs: readonly FormalizationDoc[] = formalizationDocs,
): ReadonlyMap<string, string> {
  return new Map(docs.map((doc) => [doc.fileName, renderFormalizationDoc(doc)]));
}
