import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {
  defaultAcceptanceExpressionReference,
  expressionSupportReference,
} from '#core/ir/expression-language-reference.js';
import {irIdRuleReference, irNormalizationRuleReference} from '#core/ir/normalization-reference.js';
import {staticDiagnosticReference} from '#core/static-semantics/static-diagnostic-reference.js';
import {
  surfaceSchemaReference,
  surfaceValidationRuleReference,
} from '#core/surface/surface-schema-reference.js';
import {
  surfaceWorkflowDocumentCueBoundaryReference,
  surfaceWorkflowDocumentCueSchema,
} from '#core/surface/surface-workflow-document-cue.js';
import {
  conceptChangeChecklistReference,
  docGenerationCapabilityReference,
  requirementStatusReference,
} from './formalization-process-reference.js';
import {
  renderConceptChangeChecklistReference,
  renderDefaultAcceptanceExpressionReference,
  renderDocGenerationCapabilityReference,
  renderExpressionSupportReference,
  renderIrIdRuleReference,
  renderIrNormalizationRuleReference,
  renderRequirementStatusReference,
  renderStaticDiagnosticReference,
  renderSurfaceCueBoundaryReference,
  renderSurfaceCueFieldMap,
  renderSurfaceSchemaReferenceSections,
  renderSurfaceValidationRuleReference,
} from './markdown-reference.js';
import {renderTypeReferenceSections} from './typescript-type-reference.js';

export type FormalizationDocStatus = 'normative' | 'deferred';

export type FormalizationDocSection = {
  readonly title: string;
  readonly body: readonly string[];
};

export type FormalizationDoc = {
  readonly fileName: string;
  readonly title: string;
  readonly status: FormalizationDocStatus;
  readonly generatorOwner: '@shipfox/api-workflow-language' | '@shipfox/api-workflows';
  readonly sourceOfTruth: string;
  readonly purpose: readonly string[];
  readonly normativeModel: readonly string[];
  readonly generatedLines: readonly string[];
  readonly examples: readonly string[];
  readonly addingOrChanging: readonly string[];
  readonly deferredWork: readonly string[];
  readonly extraSections?: readonly FormalizationDocSection[];
};

export const generatedSectionMarker =
  '<!-- generated by libs/api/workflow-language/scripts/generate-formalization-docs.ts; do not edit generated sections directly -->';

export const generatedSectionStart = '<!-- generated:start -->';
export const generatedSectionEnd = '<!-- generated:end -->';

const workflowIrSource = readFileSync(
  resolve(import.meta.dirname, '../core/ir/workflow-ir.ts'),
  'utf8',
);
const expressionIrSource = readFileSync(
  resolve(import.meta.dirname, '../core/ir/expression-ir.ts'),
  'utf8',
);

export const formalizationDocs: readonly FormalizationDoc[] = [
  {
    fileName: '000-requirements-ledger.md',
    title: '000 Requirements Ledger',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'docs/formalizing-shipfox-runtime/000-requirements-ledger.md',
    purpose: [
      'Track the PR1 runtime-formalization requirements, whether each one is implemented, and where the implementation or deferral is documented.',
      'This document is the repo-owned ledger for reviewers. It does not depend on temporary planning artifacts.',
    ],
    normativeModel: [
      '- Preserve the current YAML authoring surface for PR1.',
      '- Introduce a shared workflow-language package below feature packages.',
      '- Derive runtime semantics from a normalized IR at run creation.',
      '- Formalize job-level runtime behavior before step-level semantics.',
      '- Commit generated documentation whenever code-derived sections change.',
    ],
    generatedLines: [
      '- `@shipfox/api-workflow-language` owns formalization helpers and generated documentation sections.',
      '- PR1 documentation is written under `docs/formalizing-shipfox-runtime/`.',
      '- Generated docs are checked by `libs/api/workflow-language/src/docs/formalization-doc-model.test.ts`.',
      renderRequirementStatusReference(requirementStatusReference),
    ],
    examples: [
      'A requirement can be marked included when the matching code, tests, and generated docs are committed in the same slice.',
    ],
    addingOrChanging: [
      'Add a requirement row before implementing a new formalized concept, then update its status in the commit that lands the code.',
    ],
    deferredWork: ['- See the PR1 Requirement Status table for included and deferred work.'],
    extraSections: [
      {
        title: 'Related Exploratory Docs',
        body: [
          '- `010-future-platform-use-cases.md` captures future platform examples. Its YAML snippets are non-normative and do not define accepted PR1 syntax.',
        ],
      },
    ],
  },
  {
    fileName: '001-yaml-surface.md',
    title: '001 YAML Surface',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'libs/api/workflow-language/src/core/surface/surface-workflow-document.ts',
    purpose: [
      'Describe the author-facing YAML document accepted by PR1.',
      'This document tracks compatibility constraints for the surface schema owned by workflow-language.',
    ],
    normativeModel: [
      '- A workflow document has a required non-empty `name`.',
      '- `jobs` is a map keyed by job name.',
      '- `triggers` remains an optional map keyed by trigger name.',
      '- `runner`, job `runner`, and job `needs` accept either a string or a string array.',
    ],
    generatedLines: [
      '- Canonical DTO surface schema: `surfaceWorkflowDocumentSchema`.',
      '- Canonical DTO surface type: `SurfaceWorkflowDocumentDto`.',
      '- Canonical YAML parser: `parseYamlSurfaceWorkflowDocument`.',
      '- Surface compatibility mode: required workflow name, trigger map, HTTP `definition` field, SQL `definition` column.',
      '- Validate-route compatibility mode: response field `spec` and error code `invalid-definition-spec` remain stable.',
      '### Generated Surface Schema Reference',
      ...renderSurfaceSchemaReferenceSections(surfaceSchemaReference),
      renderSurfaceValidationRuleReference(surfaceValidationRuleReference),
    ],
    examples: ['A minimal document declares `name` and one job with at least one `run` step.'],
    addingOrChanging: [
      'Update the Zod schema, CUE formalization artifact, examples, compatibility tests, and generated docs together.',
    ],
    deferredWork: [
      '- Optional workflow names.',
      '- Trigger list authoring shape.',
      '- Additional surface languages.',
      '- Public wire rename from `definition` to `document`.',
    ],
  },
  {
    fileName: '002-cue-schema.md',
    title: '002 CUE Schema',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'libs/api/workflow-language/src/core/surface/surface-workflow-document-cue.ts',
    purpose: [
      'Define how PR1 uses CUE as a formalization artifact for the YAML-produced surface document shape.',
      'PR1 does not accept CUE files as workflow authoring input.',
    ],
    normativeModel: [
      '- The CUE artifact formalizes the post-YAML object shape.',
      '- Runtime and HTTP behavior remain driven by the current YAML ingestion path.',
      '- CUE tooling is optional until a dedicated toolchain decision is made.',
    ],
    generatedLines: [
      '- CUE authoring input support: deferred.',
      '- CUE schema execution in CI: deferred unless the PR adds the `cue` CLI deliberately.',
      renderSurfaceCueBoundaryReference(surfaceWorkflowDocumentCueBoundaryReference),
      renderSurfaceCueFieldMap(surfaceSchemaReference),
      `\`\`\`cue\n${surfaceWorkflowDocumentCueSchema.trim()}\n\`\`\``,
    ],
    examples: [
      'Use CUE snippets in this document to explain shape constraints, not as accepted input examples.',
    ],
    addingOrChanging: [
      'When the YAML shape changes, update the CUE artifact in the same commit and add a drift test if the artifact is code-derived.',
    ],
    deferredWork: ['- CUE as a first-class surface language.'],
  },
  {
    fileName: '003-expression-language.md',
    title: '003 Expression Language',
    status: 'deferred',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'libs/api/workflow-language/src/core/ir/expression-ir.ts',
    purpose: ['Document expression-language scope and intentionally unsupported behavior for PR1.'],
    normativeModel: [
      '- PR1 must not pass raw custom gate expressions into runtime semantics.',
      '- Default gate policy may be represented as a typed built-in concept.',
      '- Runner-reported command facts must exist before runtime expression evaluation can be meaningful.',
      '- Any future expression string must have a parser, AST, static diagnostics, evaluator, and tests before being accepted by runtime semantics.',
    ],
    generatedLines: [
      '- Expression parser implementation: deferred in PR1.',
      `- PR1 IR acceptance policy: typed \`${defaultAcceptanceExpressionReference.policyKind}\` with expression \`${defaultAcceptanceExpressionReference.expression}\`.`,
      '- PR1 runtime evaluation: job completion status is reported by the runner/job orchestration path, not by a custom expression evaluator.',
      '### Generated Expression IR Type Reference',
      ...renderTypeReferenceSections(expressionIrSource, [
        'ExprIR',
        'BinaryExprIR',
        'RefExprIR',
        'IntLiteralExprIR',
        'DefaultRunExitCodeAcceptancePolicyIR',
        'AcceptancePolicyIR',
      ]),
      renderDefaultAcceptanceExpressionReference(defaultAcceptanceExpressionReference),
      renderExpressionSupportReference(expressionSupportReference),
    ],
    examples: [
      'A default success policy can be named as a built-in rather than represented by a raw string.',
      'A future `gate.success_if: output.exit_code == 0 && tests.failed == 0` field must not be forwarded as an opaque string; it needs typed parsing and diagnostics first.',
    ],
    addingOrChanging: [
      'Add grammar, AST, parser tests, docs, and static diagnostics before accepting any new expression string.',
      'Update IR normalization so expression-bearing fields become typed expression nodes rather than raw strings.',
      'Update runtime traces only after the evaluator can consume runner facts deterministically.',
    ],
    deferredWork: [
      '- Custom `gate.success_if` parsing.',
      '- Expression typechecking over runner facts.',
      '- Runtime expression evaluator.',
      '- Runner DTOs for structured command facts.',
    ],
    extraSections: [
      {
        title: 'Future Predicate And Premise Logic',
        body: [
          'A later expression-language slice should introduce a full formal logic layer for predicates and premises. That layer is intentionally outside the current PR1 scope.',
          'In that future model, predicates are typed expressions over available facts, such as runner exit codes, structured command output, trigger payloads, job states, step states, and integration payloads.',
          'Premises describe when a semantic rule may apply. For example, a future runtime rule might require premises such as all prerequisite jobs have succeeded, the current step output is present, and the predicate evaluates to true.',
          'That logic must not be added as raw strings in `WorkflowIR`. It needs a grammar, parser, typed AST, static diagnostics, fact model, evaluator, generated docs, and golden traces before runtime rules depend on it.',
          'The current runtime transition notation remains useful without that full logic layer: job-level transitions can be formalized over `WorkflowIR` and `RuntimeState` while richer predicate and premise evaluation remains deferred.',
        ],
      },
    ],
  },
  {
    fileName: '004-core-ir.md',
    title: '004 Core IR',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'libs/api/workflow-language/src/core/ir/workflow-ir.ts',
    purpose: ['Describe the normalized semantic model that workflow execution consumes.'],
    normativeModel: [
      '- WorkflowIR is derived at run creation by `@shipfox/api-workflows`.',
      '- PR1 does not cache WorkflowIR in Postgres.',
      '- Trigger maps normalize to ordered IR trigger lists.',
      '- Job dependencies normalize to explicit dependency edges.',
      '- Run steps normalize to explicit step IDs and typed default acceptance policies.',
    ],
    generatedLines: [
      '- WorkflowIR type owner: `libs/api/workflow-language/src/core/ir/workflow-ir.ts`.',
      '- Normalizer owner: `libs/api/workflow-language/src/core/ir/normalize-surface-document.ts`.',
      '- ID helper owner: `libs/api/workflow-language/src/core/ir/ids.ts`.',
      '- Expression/default-gate owner: `libs/api/workflow-language/src/core/ir/expression-ir.ts`.',
      '- Expression IR type references are generated in `003-expression-language.md`.',
      renderIrNormalizationRuleReference(irNormalizationRuleReference),
      renderIrIdRuleReference(irIdRuleReference),
      '- The only PR1 acceptance policy in IR is `default_run_exit_code` with a typed `exit_code == 0` expression.',
      '### Generated IR Type Reference',
      ...renderTypeReferenceSections(workflowIrSource, [
        'WorkflowId',
        'TriggerId',
        'JobId',
        'StepId',
        'RunnerSelectorIR',
        'WorkflowIR',
        'TriggerIR',
        'JobIR',
        'JobDependencyIR',
        'StepIR',
        'RunStepIR',
        'RunCommandIR',
      ]),
    ],
    examples: [
      'A job dependency map such as `deploy.needs: [build, test]` becomes explicit edges `build -> deploy` and `test -> deploy`.',
      'Surface map keys `build main` and `build_main` normalize to job IDs `build-main` and `build-main-2`.',
      'Two anonymous `run: pnpm install` steps in job `build` normalize to `build.pnpm-install` and `build.pnpm-install-2`.',
    ],
    addingOrChanging: [
      'Update IR types, normalizer tests, static semantics, runtime docs, and generated docs when adding IR concepts.',
    ],
    deferredWork: [
      '- Cached WorkflowIR persistence.',
      '- Custom `gate.success_if` parsing and runtime evaluation.',
    ],
  },
  {
    fileName: '005-static-semantics.md',
    title: '005 Static Semantics',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'libs/api/workflow-language/src/core/static-semantics/diagnostic.ts',
    purpose: ['Document reusable validation rules over WorkflowIR.'],
    normativeModel: [
      '- Static diagnostics use stable IDs.',
      '- Definitions parse-time validation uses shared WorkflowIR static checks.',
      '- Run creation uses the same static checks before persisting jobs and steps.',
    ],
    generatedLines: [
      '- Diagnostic registry owner: `libs/api/workflow-language/src/core/static-semantics/diagnostic.ts`.',
      '- Static check owner: `libs/api/workflow-language/src/core/static-semantics/validate-workflow-ir.ts`.',
      '- Dependency edges point prerequisite -> dependent: `from` is the needed job, and `to` is the job that declared `needs`.',
      renderStaticDiagnosticReference(staticDiagnosticReference),
      '- Reference diagnostics are reported before cycle diagnostics because cycle analysis requires resolvable edge endpoints.',
      '- Diagnostics with a resolved author-facing job use `JobIR.sourceName`; `SS004_UNKNOWN_DEPENDENT_JOB` reports by dependency edge index because its target job is absent.',
    ],
    examples: [
      'A surface `needs: ghost` entry normalizes to an unresolved IR edge and returns `SS001_UNKNOWN_JOB_DEPENDENCY`.',
      'A malformed IR edge targeting a missing job returns `SS004_UNKNOWN_DEPENDENT_JOB`.',
      'A cycle such as `a -> b -> c -> a` returns `SS003_CYCLIC_JOB_DEPENDENCY`.',
    ],
    addingOrChanging: [
      'Add diagnostic IDs, tests, docs, and call sites for each new semantic rule.',
    ],
    deferredWork: ['- Rich runner fact validation.'],
  },
  {
    fileName: '006-runtime-transitions.md',
    title: '006 Runtime Transitions',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflows',
    sourceOfTruth: 'libs/api/workflows/src/docs/runtime-formalization-doc-model.ts',
    purpose: [
      'Catalog-only entry. The generated document body is owned by `@shipfox/api-workflows`.',
    ],
    normativeModel: [],
    generatedLines: [],
    examples: [],
    addingOrChanging: [],
    deferredWork: [],
  },
  {
    fileName: '007-durable-execution-host.md',
    title: '007 Durable Execution Host',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflows',
    sourceOfTruth: 'libs/api/workflows/src/docs/runtime-formalization-doc-model.ts',
    purpose: [
      'Catalog-only entry. The generated document body is owned by `@shipfox/api-workflows`.',
    ],
    normativeModel: [],
    generatedLines: [],
    examples: [],
    addingOrChanging: [],
    deferredWork: [],
  },
  {
    fileName: '008-adding-new-concepts.md',
    title: '008 Adding New Concepts',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth: 'docs/formalizing-shipfox-runtime/008-adding-new-concepts.md',
    purpose: ['Define the process for adding or changing formalized workflow concepts.'],
    normativeModel: [
      '- The generated concept-change checklist is the authoritative process for adding or changing formalized concepts.',
      '- Every concept starts with a requirement ledger row and an explicit classification.',
      '- Surface, expression, IR, static-semantics, runtime, and durable execution host work are conditional on that classification.',
      '- Generated docs, tests, and deferred-work notes must be updated with the affected layer.',
      '- Surface languages are authoring adapters. They must not own runtime semantics that other surfaces cannot share.',
      '- Defaults, inheritance, expression meaning, and canonical shape changes belong at the normalization/canonicalization boundary before runtime sees the workflow.',
    ],
    examples: [
      'A new authoring field starts in the ledger, then updates surface validation, CUE, IR normalization, diagnostics, docs, and tests as needed.',
    ],
    addingOrChanging: [
      'Change this process only when a PR demonstrates that the current sequence misses a required formalization layer.',
    ],
    generatedLines: [
      '- Formalized concept process version: PR1 job-level runtime formalization.',
      '- New docs should be added to `formalizationDocs` so generation and committed-output tests cover them.',
      '- Runtime-changing concepts require golden traces before durable execution host wiring.',
      '- Current normalization/canonicalization owner: `libs/api/workflow-language/src/core/ir/normalize-surface-document.ts`.',
      renderConceptChangeChecklistReference(conceptChangeChecklistReference),
    ],
    deferredWork: [
      '- Repo-local deferred task index if per-document deferred sections become too fragmented after PR1.',
    ],
    extraSections: [
      {
        title: 'Surface Language Portability Rules',
        body: [
          'The workflow language should be able to accept future authoring surfaces without making YAML semantics special. Candidate surfaces include CUE, TypeScript SDKs, Python SDKs, generated workflows, and UI builders.',
          'Equivalent workflows from different surfaces should converge before execution:',
          '```text\nYAML / CUE / TypeScript SDK / Python SDK / UI Builder\n              -> SurfaceWorkflowDocument or canonical normalized model\n              -> WorkflowIR\n              -> static semantics\n              -> runtime\n```',
          'Rules:',
          '- Surface syntax may differ; Shipfox semantics must converge.',
          '- Runtime must consume `WorkflowIR` and must not inspect which surface produced it.',
          '- Defaults and inheritance belong to normalization/canonicalization, not to runtime, database persistence, Temporal orchestration, or runner dispatch.',
          '- Expression-bearing fields must eventually parse into shared Shipfox expression IR instead of remaining surface-language strings.',
          '- Diagnostics should point back to the source surface when possible, but diagnostic meaning should be shared across surfaces.',
          '- CUE is a PR1 formalization artifact, not an accepted authoring input. If CUE later becomes canonical, the same semantic rules should move from TypeScript normalization into CUE-backed canonicalization without changing runtime consumption.',
        ],
      },
      {
        title: 'Example: Top-Level Runner Default',
        body: [
          'A surface may allow a workflow-level runner:',
          '```yaml\nrunner: ubuntu-latest\njobs:\n  build:\n    steps:\n      - run: npm test\n```',
          'This is surface syntax. It is not a runtime rule. If workflow-level `runner` means a default job runner, the default is applied during normalization/canonicalization before producing `WorkflowIR`.',
          'In PR1, that boundary is `normalizeSurfaceDocumentToWorkflowIR` in `libs/api/workflow-language/src/core/ir/normalize-surface-document.ts`:',
          '```text\nSurfaceWorkflowDocument\n  workflow.runner = "ubuntu-latest"\n  jobs.build.runner = undefined\n\n          -> normalization/canonicalization\n\nWorkflowIR\n  jobs.build.runner = ["ubuntu-latest"]\n```',
          'After this boundary, downstream layers should only see the effective job runner:',
          '```json\n{\n  "sourceName": "build",\n  "runner": ["ubuntu-latest"]\n}\n```',
          'The runtime, database persistence, Temporal orchestration, and runner dispatch must not re-implement this inheritance rule. They consume the already-normalized effective runner from `WorkflowIR`.',
          'Other surfaces expressing the same intent must normalize to the same effective IR. For example, a TypeScript SDK could expose:',
          '```ts\nworkflow("simple build")\n  .runner("ubuntu-latest")\n  .job("build", (job) => job.run("npm test"));\n```',
          'A Python SDK could expose:',
          '```python\nworkflow("simple build") \\\n  .runner("ubuntu-latest") \\\n  .job("build", lambda job: job.run("npm test"))\n```',
          'Both should normalize to a `WorkflowIR` job with `runner: ["ubuntu-latest"]` before validation, persistence, or execution.',
        ],
      },
    ],
  },
  {
    fileName: '009-doc-generation.md',
    title: '009 Doc Generation',
    status: 'normative',
    generatorOwner: '@shipfox/api-workflow-language',
    sourceOfTruth:
      'libs/api/workflow-language/scripts/generate-formalization-docs.ts and libs/api/workflows/scripts/generate-formalization-docs.ts',
    purpose: ['Explain how generated formalization documentation is produced and reviewed.'],
    normativeModel: [
      '- Generated sections are delimited by generated markers.',
      '- Generated facts are owned by the package that owns the source code they describe.',
      '- The generator must be deterministic.',
      '- Generated docs are committed with the code that changes them.',
      '- Do not include wall-clock timestamps in generated output.',
    ],
    generatedLines: [
      '- Workflow-language generator command: `pnpm --filter=@shipfox/api-workflow-language generate:docs`.',
      '- Workflows generator command: `pnpm --filter=@shipfox/api-workflows generate:docs`.',
      '- Combined Turbo generator command: `turbo generate:docs --filter=@shipfox/api-workflow-language --filter=@shipfox/api-workflows`.',
      '- Generator script owner: `libs/api/workflow-language/scripts/generate-formalization-docs.ts`.',
      '- Runtime generator script owner: `libs/api/workflows/scripts/generate-formalization-docs.ts`.',
      '- Generated content model owner: `libs/api/workflow-language/src/docs/formalization-doc-model.ts`.',
      '- Type reference extractor owner: `libs/api/workflow-language/src/docs/typescript-type-reference.ts`.',
      '- `004-core-ir.md` renders exported IR type aliases from `workflow-ir.ts` and `expression-ir.ts`.',
      '- Committed-output test owner: `libs/api/workflow-language/src/docs/formalization-doc-model.test.ts`.',
      '- Runtime committed-output test owner: `libs/api/workflows/src/docs/runtime-formalization-doc-model.test.ts`.',
      '- Generated section marker is exported as `generatedSectionMarker`.',
      renderDocGenerationCapabilityReference(docGenerationCapabilityReference),
    ],
    examples: [
      'Run the generator twice without code changes; the second run should produce no diff.',
    ],
    addingOrChanging: [
      'Update the doc model test whenever generator structure or generated section behavior changes.',
      'Do not hand-edit generated sections; update `formalization-doc-model.ts` and rerun the generator.',
      'When code-derived facts change, commit the generated Markdown in the same commit as the code.',
    ],
    deferredWork: [
      '- Broader generated coverage as IR, diagnostics, and runtime metadata are introduced.',
    ],
    extraSections: [
      {
        title: 'Review Checklist',
        body: [
          '- Run `turbo generate:docs --filter=@shipfox/api-workflow-language --filter=@shipfox/api-workflows` after changing the doc model or generated facts.',
          '- Run package tests so committed-output tests verify generated docs: `turbo test --filter=@shipfox/api-workflow-language... --filter=@shipfox/api-workflows...`.',
          '- Confirm a second generator run produces no diff.',
          '- Keep generated output free of timestamps, random ordering, environment-specific paths, and temporary planning references.',
        ],
      },
      {
        title: 'Runtime Docs Ownership',
        body: [
          '- `@shipfox/api-workflow-language` owns docs for the YAML surface, CUE formalization artifact, expression IR, core IR, static semantics, extension process, README catalog, and this generation process.',
          '- `@shipfox/api-workflows` owns generated facts for `006-runtime-transitions.md` and `007-durable-execution-host.md` because those facts describe runtime state, events, commands, Temporal workflows, activities, and persistence adapters in the workflows package.',
          '- Runtime docs must not be generated by importing `@shipfox/api-workflows` into `@shipfox/api-workflow-language`; that would invert the package dependency direction.',
          '- Use Turbo to run both package-owned generators when a change may affect multiple generated docs.',
        ],
      },
    ],
  },
];

export const workflowLanguageFormalizationDocs = formalizationDocs.filter(
  (doc) => doc.generatorOwner === '@shipfox/api-workflow-language',
);

function renderBlock(lines: readonly string[]): string {
  return lines.length === 0 ? 'None.' : lines.join('\n\n');
}

export function renderFormalizationDoc(doc: FormalizationDoc): string {
  const sections = [
    `# ${doc.title}`,
    `Status: ${doc.status}\nSource of truth: ${doc.sourceOfTruth}`,
    `## Purpose\n\n${renderBlock(doc.purpose)}`,
    `## Normative Model\n\n${renderBlock(doc.normativeModel)}\n\n${generatedSectionMarker}\n${generatedSectionStart}\n${renderBlock(doc.generatedLines)}\n${generatedSectionEnd}`,
    `## Examples\n\n${renderBlock(doc.examples)}`,
    `## Adding Or Changing This Concept\n\n${renderBlock(doc.addingOrChanging)}`,
    `## Deferred Work\n\n${renderBlock(doc.deferredWork)}`,
    ...(doc.extraSections?.map(
      (section) => `## ${section.title}\n\n${renderBlock(section.body)}`,
    ) ?? []),
  ];

  return `${sections.join('\n\n')}\n`;
}

export function renderFormalizationDocs(
  docs: readonly FormalizationDoc[] = workflowLanguageFormalizationDocs,
): ReadonlyMap<string, string> {
  return new Map(docs.map((doc) => [doc.fileName, renderFormalizationDoc(doc)]));
}
