// GENERATED by @shipfox/client-shell/vite. Do not edit.
// biome-ignore-all format: generated code has stable, reviewable output.
// biome-ignore-all assist/source/organizeImports: generated imports follow route order.
import {createRoute, createRouter} from '@tanstack/react-router';
import {buildAnchorSkeleton, isRouteImpl, type RouteImpl, type RouterContext} from '@shipfox/client-shell/runtime';
import route0Impl from "#test/search-route-impl.js";
import route1Impl from "#test/default-route-impl.js";
import route2Impl from "#test/named-route-impl.js";

function routeOptions<T extends RouteImpl>(routeImpl: T, impl: string, path: string): T['options'] {
  if (!isRouteImpl(routeImpl)) {
    throw new TypeError(`Route implementation "${impl}" for "${path}" must export default defineRoute(...).`);
  }
  return routeImpl.options;
}

const skeleton = buildAnchorSkeleton({
  navigation: [
    {
      "id": "projects",
      "scope": "workspace",
      "label": "Projects",
      "to": "/workspaces/$wid/projects/$pid/overview",
      "order": 100
    },
    {
      "id": "insights",
      "scope": "workspace",
      "label": "Insights",
      "to": "/workspaces/$wid/insights",
      "order": 200
    }
  ],
  settingsSections: [
    {
      "id": "members",
      "pathSegment": "members",
      "label": "Members",
      "icon": "users",
      "order": 100
    }
  ],
});

const route0 = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/overview",
  ...routeOptions(route0Impl, "#test/search-route-impl.js", "/workspaces/$wid/projects/$pid/overview"),
});

const route1 = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/members",
  ...routeOptions(route1Impl, "#test/default-route-impl.js", "/workspaces/$wid/settings/members"),
});

const route2 = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/insights",
  ...routeOptions(route2Impl, "#test/named-route-impl.js", "/workspaces/$wid/insights"),
});

const projectLayout = skeleton.projectLayout.addChildren([route0]);
const workspaceSettings = skeleton.workspaceSettings.addChildren([route1]);
const workspaceLayout = skeleton.workspaceLayout.addChildren([
  route2,
  projectLayout,
  workspaceSettings,
]);

export const routeTree = skeleton.rootRoute.addChildren([
  workspaceLayout,
]);

export const router = createRouter({
  routeTree,
  context: {auth: undefined, queryClient: undefined} satisfies RouterContext,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
