// GENERATED by @shipfox/client-shell/vite. Do not edit.
// biome-ignore-all format: generated code has stable, reviewable output.
// biome-ignore-all assist/source/organizeImports: generated imports follow route order.
import {createRoute, createRouter} from '@tanstack/react-router';
import {assertRouteImplFrame, buildAnchorSkeleton, parseAppSearch, stringifyAppSearch, type RouteImpl, type RouterContext} from '@shipfox/client-shell/runtime';
import * as searchRouteImplRouteModule from "#test/search-route-impl.js";
import * as defaultRouteImplRouteModule from "#test/default-route-impl.js";
import * as namedRouteImplRouteModule from "#test/named-route-impl.js";

function routeOptions<T extends RouteImpl>(routeImpl: T, impl: string, path: string): T['options'] {
  assertRouteImplFrame(routeImpl, impl, path);
  return routeImpl.options;
}

const skeleton = buildAnchorSkeleton({
  navigation: [
    {
      "id": "projects",
      "scope": "workspace",
      "label": "Projects",
      "to": "/w/$workspaceSlug/p/$projectSlug/overview",
      "order": 100
    },
    {
      "id": "insights",
      "scope": "workspace",
      "label": "Insights",
      "to": "/w/$workspaceSlug/insights",
      "order": 200
    }
  ],
  settingsSections: [
    {
      "id": "members",
      "pathSegment": "members",
      "label": "Members",
      "icon": "users",
      "order": 100,
      "scope": "workspace"
    }
  ],
});

const searchRouteImplRoute = createRoute({
  getParentRoute: () => skeleton.projectLayout,
  path: "/overview",
  ...routeOptions(searchRouteImplRouteModule.default, "#test/search-route-impl.js", "/w/$workspaceSlug/p/$projectSlug/overview"),
});

const defaultRouteImplRoute = createRoute({
  getParentRoute: () => skeleton.workspaceSettings,
  path: "/members",
  ...routeOptions(defaultRouteImplRouteModule.default, "#test/default-route-impl.js", "/w/$workspaceSlug/settings/members"),
});

const namedRouteImplRoute = createRoute({
  getParentRoute: () => skeleton.workspaceLayout,
  path: "/insights",
  ...routeOptions(namedRouteImplRouteModule.default, "#test/named-route-impl.js", "/w/$workspaceSlug/insights"),
});

const projectSettings = skeleton.projectSettings.addChildren([]);
const projectLayout = skeleton.projectLayout.addChildren([searchRouteImplRoute,
  projectSettings]);
const workspaceSettings = skeleton.workspaceSettings.addChildren([defaultRouteImplRoute]);
const workspaceLayout = skeleton.workspaceLayout.addChildren([
  namedRouteImplRoute,
  projectLayout,
  workspaceSettings,
]);

export const routeTree = skeleton.rootRoute.addChildren([
  workspaceLayout,
]);

export const router = createRouter({
  routeTree,
  context: {auth: undefined, queryClient: undefined} satisfies RouterContext,
  scrollRestoration: true,
  parseSearch: parseAppSearch,
  stringifySearch: stringifyAppSearch,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
