import type {ComposedRoute} from '#compose/compose-routes.js';
import type {NavTabEntry, SettingsSectionEntry} from '#contract.js';
import {routePathForAnchor} from '#runtime/anchors.js';

export interface GenerateAppModuleOptions {
  routes: readonly ComposedRoute[];
  navigation: readonly NavTabEntry[];
  settingsSections: readonly SettingsSectionEntry[];
}

function literal(value: unknown): string {
  return JSON.stringify(value, undefined, 2);
}

function indentedLiteral(value: unknown, indentation: number): string {
  return literal(value).replaceAll('\n', `\n${' '.repeat(indentation)}`);
}

function routeNames(routes: readonly ComposedRoute[], parent: ComposedRoute['parent']): string {
  return routes
    .map((route, index) => ({route, index}))
    .filter(({route}) => route.parent === parent)
    .map(({index}) => `route${index}`)
    .join(', ');
}

export function generateAppModule({
  routes,
  navigation,
  settingsSections,
}: GenerateAppModuleOptions): string {
  const generatedRoutes = routes.map((route) => ({
    ...route,
    routePath: routePathForAnchor(route.parent, route.path),
  }));
  const imports = routes
    .map((route, index) => `import route${index}Impl from ${literal(route.impl)};`)
    .join('\n');
  const routeDeclarations = generatedRoutes
    .map(
      (route, index) => `const route${index} = createRoute({
  getParentRoute: () => ${route.parent === 'root' ? 'skeleton.rootRoute' : `skeleton.${route.parent}`},
  path: ${literal(route.routePath)},
  ...route${index}Impl.options,
});`,
    )
    .join('\n\n');
  const rootRoutes = routeNames(generatedRoutes, 'root');
  const workspaceLayoutRoutes = routeNames(generatedRoutes, 'workspaceLayout');
  const projectLayoutRoutes = routeNames(generatedRoutes, 'projectLayout');
  const workspaceSettingsRoutes = routeNames(generatedRoutes, 'workspaceSettings');
  const rootChildren = [rootRoutes, 'workspaceLayout'].filter(Boolean).join(',\n  ');

  return `// GENERATED by @shipfox/client-shell/vite. Do not edit.
// biome-ignore-all format: generated code has stable, reviewable output.
// biome-ignore-all assist/source/organizeImports: generated imports follow route order.
import {createRoute, createRouter} from '@tanstack/react-router';
import {buildAnchorSkeleton, type RouterContext} from '@shipfox/client-shell';
${imports}

const skeleton = buildAnchorSkeleton({
  navigation: ${indentedLiteral(navigation, 2)},
  settingsSections: ${indentedLiteral(settingsSections, 2)},
});

${routeDeclarations}

const projectLayout = skeleton.projectLayout.addChildren([${projectLayoutRoutes}]);
const workspaceSettings = skeleton.workspaceSettings.addChildren([${workspaceSettingsRoutes}]);
const workspaceLayout = skeleton.workspaceLayout.addChildren([
  ${workspaceLayoutRoutes}${workspaceLayoutRoutes ? ',' : ''}
  projectLayout,
  workspaceSettings,
]);

export const routeTree = skeleton.rootRoute.addChildren([
  ${rootChildren},
]);

export const router = createRouter({
  routeTree,
  context: {auth: undefined, queryClient: undefined} satisfies RouterContext,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
`;
}
