export {
  ANNOTATION_CONTEXT_MAX_LENGTH,
  ANNOTATION_STYLES,
  type AnnotationDto,
  type AnnotationStyleDto,
  annotationDtoSchema,
  annotationStyleSchema,
  type LeasedWriteAnnotationOperationDto,
  type LeasedWriteAnnotationsBodyDto,
  type LeasedWriteAnnotationsResponseDto,
  leasedWriteAnnotationOperationSchema,
  leasedWriteAnnotationsBodySchema,
  leasedWriteAnnotationsResponseSchema,
  type ReadAnnotationsResponseDto,
  readAnnotationsResponseSchema,
} from '#schemas/index.js';
