import {readdir, readFile, writeFile} from 'node:fs/promises';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parse as parseYaml} from 'yaml';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const assetsRoot = join(packageRoot, 'assets');
const outputPath = join(packageRoot, 'src/generated/assets.ts');

const templates = [];
for (const entry of await readdir(assetsRoot, {withFileTypes: true})) {
  if (!entry.isDirectory()) continue;

  const templateRoot = join(assetsRoot, entry.name);
  const manifestPath = join(templateRoot, 'template.yaml');
  const workflowPath = join(templateRoot, 'workflow.yml');
  const guidePath = join(templateRoot, 'GUIDE.md');
  const parts = {};

  for (const roleEntry of await readdir(join(templateRoot, 'parts'), {withFileTypes: true})) {
    if (!roleEntry.isDirectory()) continue;
    const roleParts = {};
    for (const providerEntry of await readdir(join(templateRoot, 'parts', roleEntry.name), {
      withFileTypes: true,
    })) {
      if (!providerEntry.isFile() || !providerEntry.name.endsWith('.yml')) continue;
      const provider = providerEntry.name.slice(0, -4);
      roleParts[provider] = parseYaml(
        await readFile(join(templateRoot, 'parts', roleEntry.name, providerEntry.name), 'utf8'),
      );
    }
    parts[roleEntry.name] = roleParts;
  }

  templates.push({
    manifest: await readFile(manifestPath, 'utf8'),
    workflow: await readFile(workflowPath, 'utf8'),
    guide: await readFile(guidePath, 'utf8'),
    parts,
  });
}

templates.sort((left, right) => left.manifest.localeCompare(right.manifest));
const generated = `/* Generated by scripts/embed-assets.mjs. Do not edit by hand. */\n\nimport type {EmbeddedWorkflowTemplateAsset} from '../loader.js';\n\nexport const embeddedWorkflowTemplateAssets: readonly EmbeddedWorkflowTemplateAsset[] = ${JSON.stringify(templates, null, 2)};\n`;
await writeFile(outputPath, generated);
