import {readdir, readFile, writeFile} from 'node:fs/promises';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parse as parseYaml} from 'yaml';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const assetsRoot = join(packageRoot, 'assets');
const outputPath = join(packageRoot, 'src/generated/assets.ts');
const modelTiersPath = join(assetsRoot, 'model-tiers.yaml');
const setupGuideMarkdown = await readFile(join(assetsRoot, 'playbook.md'), 'utf8');
const setupGuideRevision = setupGuideMarkdown.match(/^<!-- revision: (?<revision>[1-9]\d*) -->$/mu)
  ?.groups?.revision;
if (setupGuideRevision === undefined) {
  throw new Error('assets/playbook.md must declare a positive integer revision.');
}

const templates = [];
for (const entry of await readdir(assetsRoot, {withFileTypes: true})) {
  if (!entry.isDirectory()) continue;

  const templateRoot = join(assetsRoot, entry.name);
  const manifestPath = join(templateRoot, 'template.yaml');
  const workflowPath = join(templateRoot, 'workflow.yml');
  const guidePath = join(templateRoot, 'GUIDE.md');
  const parts = {};

  for (const roleEntry of await readdir(join(templateRoot, 'parts'), {withFileTypes: true})) {
    if (!roleEntry.isDirectory()) continue;
    const roleParts = {};
    for (const providerEntry of await readdir(join(templateRoot, 'parts', roleEntry.name), {
      withFileTypes: true,
    })) {
      if (!providerEntry.isFile() || !providerEntry.name.endsWith('.yml')) continue;
      const provider = providerEntry.name.slice(0, -4);
      const partPath = join(templateRoot, 'parts', roleEntry.name, providerEntry.name);
      const parsedPart = parseYaml(await readFile(partPath, 'utf8'));
      if (
        parsedPart === null ||
        typeof parsedPart !== 'object' ||
        Array.isArray(parsedPart) ||
        Object.values(parsedPart).some((value) => typeof value !== 'string')
      ) {
        throw new Error(
          `Invalid provider part file ${partPath}: expected a YAML map of string blocks.`,
        );
      }
      roleParts[provider] = parsedPart;
    }
    parts[roleEntry.name] = roleParts;
  }

  templates.push({
    manifest: await readFile(manifestPath, 'utf8'),
    workflow: await readFile(workflowPath, 'utf8'),
    guide: await readFile(guidePath, 'utf8'),
    parts,
  });
}

templates.sort((left, right) => left.manifest.localeCompare(right.manifest));
const modelTiers = await readFile(modelTiersPath, 'utf8');
const modelTiersLiteral = JSON.stringify(modelTiers).slice(1, -1).replaceAll("'", "\\'");
const generated = `/* Generated by scripts/embed-assets.mjs. Do not edit by hand. */
/* biome-ignore-all lint/suspicious/noTemplateCurlyInString: Workflow expressions are embedded as literal strings. */

import type {EmbeddedWorkflowTemplateAsset, WorkflowSetupGuide} from '../loader.js';

export const embeddedWorkflowSetupGuide: WorkflowSetupGuide = {
  revision: ${setupGuideRevision},
  guide_markdown:
    ${JSON.stringify(setupGuideMarkdown)},
};

export const embeddedWorkflowTemplateAssets: readonly EmbeddedWorkflowTemplateAsset[] = ${JSON.stringify(templates, null, 2)};
export const embeddedModelTiers =
  '${modelTiersLiteral}';
`;
await writeFile(outputPath, generated);
