import {
  type SimpleIcon,
  siAirtable,
  siAmazonwebservices,
  siAppstore,
  siArgo,
  siAsana,
  siBetterstack,
  siBitbucket,
  siBugsnag,
  siBuildkite,
  siCircleci,
  siCloudflare,
  siCoda,
  siConfluence,
  siDatadog,
  siDbt,
  siDiscord,
  siElastic,
  siExpo,
  siFigma,
  siFlydotio,
  siGitbook,
  siGitea,
  siGitlab,
  siGmail,
  siGooglebigquery,
  siGooglecalendar,
  siGooglechat,
  siGooglecloud,
  siGoogledrive,
  siGoogleplay,
  siGooglesheets,
  siGrafana,
  siGraphite,
  siHubspot,
  siIntercom,
  siJenkins,
  siJira,
  siLoom,
  siMattermost,
  siMetabase,
  siMiro,
  siMixpanel,
  siNetlify,
  siNewrelic,
  siPagerduty,
  siPulumi,
  siRender,
  siSalesforce,
  siShortcut,
  siSnowflake,
  siSnyk,
  siSocket,
  siSonarqube,
  siSplunk,
  siStatuspage,
  siStripe,
  siSupabase,
  siTerraform,
  siTrello,
  siVercel,
  siZendesk,
} from 'simple-icons';
import type {CatalogCategory, RequestableIntegration} from '@/lib/integration-catalog';
import {requestableIntegrationIconPaths} from '@/lib/requestable-integration-icons';

interface RequestableIntegrationDefinition {
  slug: string;
  name: string;
  summary: string;
  category: CatalogCategory;
  aliases: string[];
  icon?: SimpleIcon;
}

// Integrations Shipfox can build for a workspace that asks. Once one ships with
// its own docs pages, remove it from this list.
const definitions: readonly RequestableIntegrationDefinition[] = [
  {
    slug: 'gitlab',
    name: 'GitLab',
    summary:
      'Trigger workflows from merge requests and pipelines, and check out GitLab repositories.',
    category: 'source-control',
    aliases: ['git', 'vcs', 'merge request'],
    icon: siGitlab,
  },
  {
    slug: 'bitbucket',
    name: 'Bitbucket',
    summary: 'Trigger workflows from pull requests and check out Bitbucket repositories.',
    category: 'source-control',
    aliases: ['git', 'vcs', 'atlassian'],
    icon: siBitbucket,
  },
  {
    slug: 'azure-devops',
    name: 'Azure DevOps',
    summary: 'Trigger workflows from Azure Repos pull requests and Azure Boards work items.',
    category: 'source-control',
    aliases: ['git', 'vcs', 'ado', 'azure repos', 'azure boards', 'microsoft'],
  },
  {
    slug: 'gitea',
    name: 'Gitea',
    summary:
      'Trigger workflows from Gitea pushes and pull requests, and check out self-hosted repositories.',
    category: 'source-control',
    aliases: ['git', 'vcs', 'forgejo', 'self-hosted'],
    icon: siGitea,
  },
  {
    slug: 'graphite',
    name: 'Graphite',
    summary: 'React to stacked pull request updates and merge queue results.',
    category: 'source-control',
    aliases: ['stacks', 'merge queue', 'code review'],
    icon: siGraphite,
  },
  {
    slug: 'circleci',
    name: 'CircleCI',
    summary: 'Start workflows when CircleCI jobs fail and read job logs to explain the failure.',
    category: 'ci-cd',
    aliases: ['ci', 'build'],
    icon: siCircleci,
  },
  {
    slug: 'buildkite',
    name: 'Buildkite',
    summary: 'Start workflows when Buildkite builds fail and read job logs.',
    category: 'ci-cd',
    aliases: ['ci', 'build'],
    icon: siBuildkite,
  },
  {
    slug: 'jenkins',
    name: 'Jenkins',
    summary: 'Start workflows when Jenkins jobs fail and read console output.',
    category: 'ci-cd',
    aliases: ['ci', 'build'],
    icon: siJenkins,
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    summary: 'React to failed Vercel deployments and read build logs and preview URLs.',
    category: 'ci-cd',
    aliases: ['deploy', 'preview', 'hosting'],
    icon: siVercel,
  },
  {
    slug: 'netlify',
    name: 'Netlify',
    summary: 'React to failed Netlify deploys and read build logs.',
    category: 'ci-cd',
    aliases: ['deploy', 'preview', 'hosting'],
    icon: siNetlify,
  },
  {
    slug: 'argo-cd',
    name: 'Argo CD',
    summary: 'React to Argo CD sync failures and read application health.',
    category: 'ci-cd',
    aliases: ['deploy', 'gitops', 'kubernetes', 'k8s'],
    icon: siArgo,
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    summary: 'React to Workers and Pages deployments and read their logs.',
    category: 'ci-cd',
    aliases: ['deploy', 'workers', 'pages', 'cdn'],
    icon: siCloudflare,
  },
  {
    slug: 'render',
    name: 'Render',
    summary: 'React to failed Render deploys and read service logs.',
    category: 'ci-cd',
    aliases: ['deploy', 'hosting'],
    icon: siRender,
  },
  {
    slug: 'fly-io',
    name: 'Fly.io',
    summary: 'React to Fly.io deploys and read machine logs.',
    category: 'ci-cd',
    aliases: ['deploy', 'hosting'],
    icon: siFlydotio,
  },
  {
    slug: 'asana',
    name: 'Asana',
    summary: 'Trigger workflows from Asana tasks and let agents update and comment on them.',
    category: 'issue-tracking',
    aliases: ['tasks', 'project management'],
    icon: siAsana,
  },
  {
    slug: 'shortcut',
    name: 'Shortcut',
    summary: 'Trigger workflows from Shortcut stories and let agents update them.',
    category: 'issue-tracking',
    aliases: ['stories', 'clubhouse', 'tickets'],
    icon: siShortcut,
  },
  {
    slug: 'monday',
    name: 'monday.com',
    summary: 'Trigger workflows from monday.com items and let agents update boards.',
    category: 'issue-tracking',
    aliases: ['tasks', 'project management', 'boards'],
  },
  {
    slug: 'trello',
    name: 'Trello',
    summary: 'Trigger workflows from Trello cards and let agents move and comment on them.',
    category: 'issue-tracking',
    aliases: ['kanban', 'boards', 'atlassian'],
    icon: siTrello,
  },
  {
    slug: 'youtrack',
    name: 'YouTrack',
    summary: 'Trigger workflows from YouTrack issues and let agents update them.',
    category: 'issue-tracking',
    aliases: ['jetbrains', 'tickets'],
  },
  {
    slug: 'plane',
    name: 'Plane',
    summary: 'Trigger workflows from Plane issues and let agents update them.',
    category: 'issue-tracking',
    aliases: ['tickets', 'project management'],
  },
  {
    slug: 'confluence',
    name: 'Confluence',
    summary: 'Let agents search and read Confluence pages and publish reports to a space.',
    category: 'docs-knowledge',
    aliases: ['wiki', 'atlassian', 'documentation'],
    icon: siConfluence,
  },
  {
    slug: 'google-drive',
    name: 'Google Drive',
    summary: 'Let agents search and read Google Docs, Sheets, and Drive files.',
    category: 'docs-knowledge',
    aliases: ['google docs', 'gdrive', 'google workspace', 'files'],
    icon: siGoogledrive,
  },
  {
    slug: 'coda',
    name: 'Coda',
    summary: 'Let agents read Coda docs and update their tables.',
    category: 'docs-knowledge',
    aliases: ['wiki', 'documentation'],
    icon: siCoda,
  },
  {
    slug: 'gitbook',
    name: 'GitBook',
    summary: 'Let agents read GitBook spaces and propose content changes.',
    category: 'docs-knowledge',
    aliases: ['wiki', 'documentation'],
    icon: siGitbook,
  },
  {
    slug: 'datadog',
    name: 'Datadog',
    summary: 'Start workflows from monitor alerts and let agents query metrics, logs, and traces.',
    category: 'observability',
    aliases: ['apm', 'metrics', 'logs', 'monitoring', 'alerts'],
    icon: siDatadog,
  },
  {
    slug: 'grafana',
    name: 'Grafana',
    summary:
      'Start workflows from Grafana alerts and let agents query dashboards and data sources.',
    category: 'observability',
    aliases: ['prometheus', 'loki', 'metrics', 'alerts'],
    icon: siGrafana,
  },
  {
    slug: 'new-relic',
    name: 'New Relic',
    summary: 'Start workflows from New Relic alerts and let agents run NRQL queries.',
    category: 'observability',
    aliases: ['apm', 'metrics', 'monitoring'],
    icon: siNewrelic,
  },
  {
    slug: 'honeycomb',
    name: 'Honeycomb',
    summary: 'Start workflows from Honeycomb triggers and let agents query traces.',
    category: 'observability',
    aliases: ['tracing', 'opentelemetry', 'otel'],
  },
  {
    slug: 'dash0',
    name: 'Dash0',
    summary: 'Start workflows from Dash0 checks and let agents query OpenTelemetry data.',
    category: 'observability',
    aliases: ['opentelemetry', 'otel', 'logs', 'tracing'],
  },
  {
    slug: 'splunk',
    name: 'Splunk',
    summary: 'Start workflows from Splunk alerts and let agents run searches.',
    category: 'observability',
    aliases: ['logs', 'siem'],
    icon: siSplunk,
  },
  {
    slug: 'elastic',
    name: 'Elastic',
    summary: 'Start workflows from Elastic alerts and let agents search logs.',
    category: 'observability',
    aliases: ['elasticsearch', 'kibana', 'elk', 'logs'],
    icon: siElastic,
  },
  {
    slug: 'axiom',
    name: 'Axiom',
    summary: 'Let agents query Axiom logs and events.',
    category: 'observability',
    aliases: ['logs', 'events'],
  },
  {
    slug: 'rollbar',
    name: 'Rollbar',
    summary: 'Start workflows from Rollbar errors and read occurrences and stack traces.',
    category: 'observability',
    aliases: ['errors', 'crash', 'exceptions'],
  },
  {
    slug: 'bugsnag',
    name: 'Bugsnag',
    summary: 'Start workflows from Bugsnag errors and read stack traces.',
    category: 'observability',
    aliases: ['errors', 'crash', 'exceptions'],
    icon: siBugsnag,
  },
  {
    slug: 'amplitude',
    name: 'Amplitude',
    summary: 'Let agents query Amplitude charts and events to explain product changes.',
    category: 'product-analytics',
    aliases: ['analytics', 'events', 'experiments'],
  },
  {
    slug: 'mixpanel',
    name: 'Mixpanel',
    summary: 'Let agents query Mixpanel reports and events.',
    category: 'product-analytics',
    aliases: ['analytics', 'events'],
    icon: siMixpanel,
  },
  {
    slug: 'segment',
    name: 'Segment',
    summary: 'Trigger workflows from Segment events and let agents inspect tracking plans.',
    category: 'product-analytics',
    aliases: ['cdp', 'tracking', 'twilio'],
  },
  {
    slug: 'launchdarkly',
    name: 'LaunchDarkly',
    summary: 'React to flag changes and let agents read and toggle LaunchDarkly flags.',
    category: 'product-analytics',
    aliases: ['feature flags', 'rollout'],
  },
  {
    slug: 'statsig',
    name: 'Statsig',
    summary: 'React to experiment results and let agents read Statsig gates and experiments.',
    category: 'product-analytics',
    aliases: ['feature flags', 'experiments', 'a/b testing'],
  },
  {
    slug: 'growthbook',
    name: 'GrowthBook',
    summary: 'Let agents read GrowthBook flags and experiment results.',
    category: 'product-analytics',
    aliases: ['feature flags', 'experiments', 'a/b testing'],
  },
  {
    slug: 'pagerduty',
    name: 'PagerDuty',
    summary:
      'Start workflows when an incident opens and let agents add notes or acknowledge alerts.',
    category: 'incident-management',
    aliases: ['on-call', 'pager', 'alerts', 'incidents'],
    icon: siPagerduty,
  },
  {
    slug: 'incident-io',
    name: 'incident.io',
    summary: 'Start workflows when an incident is declared and post findings to its channel.',
    category: 'incident-management',
    aliases: ['on-call', 'incidents', 'postmortem'],
  },
  {
    slug: 'rootly',
    name: 'Rootly',
    summary: 'Start workflows from Rootly incidents and add findings to their timeline.',
    category: 'incident-management',
    aliases: ['on-call', 'incidents', 'postmortem'],
  },
  {
    slug: 'firehydrant',
    name: 'FireHydrant',
    summary: 'Start workflows from FireHydrant incidents and add findings to their timeline.',
    category: 'incident-management',
    aliases: ['on-call', 'incidents', 'postmortem'],
  },
  {
    slug: 'jira-service-management',
    name: 'Jira Service Management',
    summary: 'Trigger workflows from service requests and alerts, and let agents update them.',
    category: 'incident-management',
    aliases: ['jsm', 'opsgenie', 'itsm', 'on-call', 'atlassian'],
    icon: siJira,
  },
  {
    slug: 'statuspage',
    name: 'Atlassian Statuspage',
    summary: 'Let agents draft and publish incident updates on your status page.',
    category: 'incident-management',
    aliases: ['status page', 'incidents', 'atlassian'],
    icon: siStatuspage,
  },
  {
    slug: 'better-stack',
    name: 'Better Stack',
    summary: 'Start workflows from uptime and log alerts and read incident details.',
    category: 'incident-management',
    aliases: ['uptime', 'better uptime', 'logtail', 'on-call'],
    icon: siBetterstack,
  },
  {
    slug: 'microsoft-teams',
    name: 'Microsoft Teams',
    summary: 'Trigger workflows from Teams messages and post results to channels.',
    category: 'messaging',
    aliases: ['chat', 'msteams', 'microsoft 365'],
  },
  {
    slug: 'discord',
    name: 'Discord',
    summary: 'Trigger workflows from Discord messages and post results to channels.',
    category: 'messaging',
    aliases: ['chat', 'community'],
    icon: siDiscord,
  },
  {
    slug: 'google-chat',
    name: 'Google Chat',
    summary: 'Trigger workflows from Google Chat messages and post results to spaces.',
    category: 'messaging',
    aliases: ['chat', 'google workspace'],
    icon: siGooglechat,
  },
  {
    slug: 'mattermost',
    name: 'Mattermost',
    summary: 'Trigger workflows from Mattermost messages and post results to channels.',
    category: 'messaging',
    aliases: ['chat', 'self-hosted'],
    icon: siMattermost,
  },
  {
    slug: 'gmail',
    name: 'Gmail',
    summary: 'Trigger workflows from incoming email and let agents draft and send replies.',
    category: 'messaging',
    aliases: ['email', 'google workspace'],
    icon: siGmail,
  },
  {
    slug: 'outlook',
    name: 'Outlook',
    summary: 'Trigger workflows from incoming email and let agents draft and send replies.',
    category: 'messaging',
    aliases: ['email', 'microsoft 365', 'office 365'],
  },
  {
    slug: 'snyk',
    name: 'Snyk',
    summary: 'Start workflows from new Snyk vulnerabilities and let agents open fix pull requests.',
    category: 'security',
    aliases: ['vulnerabilities', 'dependencies', 'sca'],
    icon: siSnyk,
  },
  {
    slug: 'socket',
    name: 'Socket',
    summary: 'React to risky dependency alerts and read Socket package reports.',
    category: 'security',
    aliases: ['supply chain', 'dependencies', 'npm'],
    icon: siSocket,
  },
  {
    slug: 'semgrep',
    name: 'Semgrep',
    summary: 'Start workflows from Semgrep findings and let agents triage or fix them.',
    category: 'security',
    aliases: ['sast', 'code scanning'],
  },
  {
    slug: 'sonarqube',
    name: 'SonarQube Cloud',
    summary: 'Start workflows from failed quality gates and read SonarQube issues.',
    category: 'security',
    aliases: ['sonarcloud', 'sonar', 'code quality'],
    icon: siSonarqube,
  },
  {
    slug: 'gitguardian',
    name: 'GitGuardian',
    summary: 'Start workflows from leaked secret alerts and let agents help resolve them.',
    category: 'security',
    aliases: ['secrets', 'secret scanning'],
  },
  {
    slug: 'wiz',
    name: 'Wiz',
    summary: 'Start workflows from Wiz issues and let agents read cloud security findings.',
    category: 'security',
    aliases: ['cloud security', 'cspm'],
  },
  {
    slug: 'vanta',
    name: 'Vanta',
    summary: 'Let agents read failing Vanta tests and gather evidence for controls.',
    category: 'security',
    aliases: ['compliance', 'soc 2', 'iso 27001'],
  },
  {
    slug: 'drata',
    name: 'Drata',
    summary: 'Let agents read failing Drata monitors and gather evidence for controls.',
    category: 'security',
    aliases: ['compliance', 'soc 2', 'iso 27001'],
  },
  {
    slug: 'aws',
    name: 'AWS',
    summary:
      'React to CloudWatch alarms and let agents read logs and resources in your AWS accounts.',
    category: 'cloud',
    aliases: ['amazon web services', 'cloudwatch', 'ec2', 'lambda'],
    icon: siAmazonwebservices,
  },
  {
    slug: 'google-cloud',
    name: 'Google Cloud',
    summary:
      'React to Cloud Monitoring alerts and let agents read logs and resources in your projects.',
    category: 'cloud',
    aliases: ['gcp', 'cloud run', 'gke'],
    icon: siGooglecloud,
  },
  {
    slug: 'azure',
    name: 'Microsoft Azure',
    summary:
      'React to Azure Monitor alerts and let agents read logs and resources in your subscriptions.',
    category: 'cloud',
    aliases: ['azure monitor', 'aks', 'microsoft'],
  },
  {
    slug: 'hcp-terraform',
    name: 'HCP Terraform',
    summary: 'Start workflows from Terraform runs and let agents read plans and drift.',
    category: 'cloud',
    aliases: ['terraform cloud', 'iac', 'hashicorp'],
    icon: siTerraform,
  },
  {
    slug: 'pulumi',
    name: 'Pulumi',
    summary:
      'Start workflows from Pulumi deployments and let agents read previews and stack state.',
    category: 'cloud',
    aliases: ['iac'],
    icon: siPulumi,
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    summary: 'Let agents inspect Supabase projects, schemas, and logs.',
    category: 'data',
    aliases: ['postgres', 'database'],
    icon: siSupabase,
  },
  {
    slug: 'neon',
    name: 'Neon',
    summary: 'Let agents inspect Neon branches, schemas, and slow queries.',
    category: 'data',
    aliases: ['postgres', 'database'],
  },
  {
    slug: 'snowflake',
    name: 'Snowflake',
    summary: 'Let agents run read-only queries against Snowflake warehouses.',
    category: 'data',
    aliases: ['data warehouse', 'sql'],
    icon: siSnowflake,
  },
  {
    slug: 'bigquery',
    name: 'BigQuery',
    summary: 'Let agents run read-only queries against BigQuery datasets.',
    category: 'data',
    aliases: ['data warehouse', 'sql', 'google cloud'],
    icon: siGooglebigquery,
  },
  {
    slug: 'dbt',
    name: 'dbt Cloud',
    summary: 'Start workflows when dbt jobs fail and read run logs.',
    category: 'data',
    aliases: ['data transformation', 'sql'],
    icon: siDbt,
  },
  {
    slug: 'metabase',
    name: 'Metabase',
    summary: 'Let agents read Metabase questions and dashboards.',
    category: 'data',
    aliases: ['bi', 'dashboards'],
    icon: siMetabase,
  },
  {
    slug: 'google-sheets',
    name: 'Google Sheets',
    summary: 'Let agents read Google Sheets and append rows.',
    category: 'data',
    aliases: ['spreadsheet', 'google workspace'],
    icon: siGooglesheets,
  },
  {
    slug: 'airtable',
    name: 'Airtable',
    summary: 'Trigger workflows from Airtable records and let agents update bases.',
    category: 'data',
    aliases: ['spreadsheet', 'database'],
    icon: siAirtable,
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    summary: 'Trigger workflows from Zendesk tickets and let agents investigate and draft replies.',
    category: 'support',
    aliases: ['helpdesk', 'tickets', 'customer support'],
    icon: siZendesk,
  },
  {
    slug: 'intercom',
    name: 'Intercom',
    summary:
      'Trigger workflows from Intercom conversations and let agents investigate and draft replies.',
    category: 'support',
    aliases: ['helpdesk', 'chat', 'customer support'],
    icon: siIntercom,
  },
  {
    slug: 'front',
    name: 'Front',
    summary: 'Trigger workflows from Front conversations and let agents draft replies.',
    category: 'support',
    aliases: ['shared inbox', 'email', 'customer support'],
  },
  {
    slug: 'pylon',
    name: 'Pylon',
    summary: 'Trigger workflows from Pylon issues and let agents investigate them.',
    category: 'support',
    aliases: ['helpdesk', 'customer support'],
  },
  {
    slug: 'plain',
    name: 'Plain',
    summary: 'Trigger workflows from Plain threads and let agents investigate and draft replies.',
    category: 'support',
    aliases: ['helpdesk', 'customer support'],
  },
  {
    slug: 'freshdesk',
    name: 'Freshdesk',
    summary: 'Trigger workflows from Freshdesk tickets and let agents draft replies.',
    category: 'support',
    aliases: ['helpdesk', 'tickets', 'customer support'],
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    summary: 'Trigger workflows from HubSpot deals and tickets, and let agents update records.',
    category: 'support',
    aliases: ['crm', 'sales', 'marketing'],
    icon: siHubspot,
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    summary:
      'Trigger workflows from Salesforce cases and opportunities, and let agents update records.',
    category: 'support',
    aliases: ['crm', 'sales', 'sfdc'],
    icon: siSalesforce,
  },
  {
    slug: 'figma',
    name: 'Figma',
    summary: 'Let agents read Figma files and comments to implement or review designs.',
    category: 'design',
    aliases: ['design', 'mockups'],
    icon: siFigma,
  },
  {
    slug: 'miro',
    name: 'Miro',
    summary: 'Let agents read Miro boards and add notes or diagrams.',
    category: 'design',
    aliases: ['whiteboard', 'diagrams'],
    icon: siMiro,
  },
  {
    slug: 'loom',
    name: 'Loom',
    summary: 'Let agents read the transcripts of Loom videos linked from issues and pull requests.',
    category: 'design',
    aliases: ['video', 'screen recording'],
    icon: siLoom,
  },
  {
    slug: 'productboard',
    name: 'Productboard',
    summary: 'Trigger workflows from Productboard features and read linked feedback.',
    category: 'design',
    aliases: ['roadmap', 'feedback'],
  },
  {
    slug: 'canny',
    name: 'Canny',
    summary: 'Trigger workflows from Canny posts and votes.',
    category: 'design',
    aliases: ['feature requests', 'feedback', 'roadmap'],
  },
  {
    slug: 'app-store-connect',
    name: 'App Store Connect',
    summary: 'React to TestFlight builds and App Store review status, and read crash reports.',
    category: 'mobile-release',
    aliases: ['ios', 'testflight', 'apple'],
    icon: siAppstore,
  },
  {
    slug: 'google-play-console',
    name: 'Google Play Console',
    summary: 'React to Google Play release status and read Android vitals.',
    category: 'mobile-release',
    aliases: ['android', 'play store'],
    icon: siGoogleplay,
  },
  {
    slug: 'expo',
    name: 'Expo',
    summary: 'React to EAS builds and updates, and read build logs.',
    category: 'mobile-release',
    aliases: ['eas', 'react native'],
    icon: siExpo,
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    summary:
      'Start workflows from Stripe events and let agents read customers, subscriptions, and payments.',
    category: 'business',
    aliases: ['billing', 'payments'],
    icon: siStripe,
  },
  {
    slug: 'google-calendar',
    name: 'Google Calendar',
    summary: 'Start workflows from calendar events and let agents schedule meetings.',
    category: 'business',
    aliases: ['calendar', 'meetings', 'google workspace'],
    icon: siGooglecalendar,
  },
];

export const requestableIntegrations: readonly RequestableIntegration[] = definitions.map(
  ({category, icon, ...definition}) => {
    const iconPath = icon?.path ?? requestableIntegrationIconPaths[definition.slug];
    if (!iconPath) throw new Error(`Integration "${definition.slug}" has no logo.`);
    return {...definition, categories: [category], iconPath};
  },
);
