import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {
  readRuntimeGoldenTrace,
  runtimeGoldenTraceReferences,
} from '#core/runtime/runtime-golden-trace-reference.js';
import {
  durableExecutionHostActivityReference,
  durableExecutionHostCommandAdapterReference,
  durableExecutionHostWorkflowReference,
} from '#temporal/durable-execution-host-reference.js';
import {renderRuntimeTypeReferenceSections} from './runtime-typescript-reference.js';

export type RuntimeFormalizationDoc = Readonly<{
  fileName: string;
  title: string;
  status: 'normative';
  sourceOfTruth: string;
  purpose: readonly string[];
  normativeModel: readonly string[];
  generatedLines: readonly string[];
  examples: readonly string[];
  addingOrChanging: readonly string[];
  deferredWork: readonly string[];
}>;

export const runtimeGeneratedSectionMarker =
  '<!-- generated by libs/api/workflows/scripts/generate-formalization-docs.ts; do not edit generated sections directly -->';

export const runtimeGeneratedSectionStart = '<!-- generated:start -->';
export const runtimeGeneratedSectionEnd = '<!-- generated:end -->';

type RuntimeTransitionRuleReference = Readonly<{
  rule: string;
  input: string;
  output: string;
}>;

const runtimeStateSource = readFileSync(
  resolve(import.meta.dirname, '../core/runtime/runtime-state.ts'),
  'utf8',
);
const runtimeEventSource = readFileSync(
  resolve(import.meta.dirname, '../core/runtime/runtime-event.ts'),
  'utf8',
);
const runtimeCommandSource = readFileSync(
  resolve(import.meta.dirname, '../core/runtime/runtime-command.ts'),
  'utf8',
);

const runtimeTransitionRuleReference: readonly RuntimeTransitionRuleReference[] = [
  {
    rule: 'Terminal run guard',
    input: '`RuntimeState.run.status` is `succeeded` or `failed`.',
    output: 'Return a cloned state and emit no commands.',
  },
  {
    rule: '`run_started`',
    input: 'Run is not terminal.',
    output: 'Set run status to `running`, then reconcile jobs.',
  },
  {
    rule: '`job_completed`',
    input: 'Matching job exists and is `running`.',
    output: 'Set the job status to the event status, then reconcile jobs; otherwise no-op.',
  },
  {
    rule: 'Blocked pending jobs',
    input: 'Pending job depends on a failed or cancelled job.',
    output: 'Mark it `cancelled` and emit `cancel_job`.',
  },
  {
    rule: 'Ready pending jobs',
    input: 'Pending job has all dependencies `succeeded`.',
    output: 'Mark it `running` and emit `start_job`.',
  },
  {
    rule: 'No progress',
    input: 'Pending jobs remain, no job is running, and no job started.',
    output: 'Cancel remaining pending jobs.',
  },
  {
    rule: 'Terminal jobs',
    input: 'Every job is `succeeded`, `failed`, or `cancelled`.',
    output: 'Complete the run as `succeeded` only when no job failed or was cancelled.',
  },
];

export const runtimeFormalizationDocs: readonly RuntimeFormalizationDoc[] = [
  {
    fileName: '006-runtime-transitions.md',
    title: '006 Runtime Transitions',
    status: 'normative',
    sourceOfTruth: 'libs/api/workflows/src/core/runtime/',
    purpose: ['Document the pure job-level runtime transition system.'],
    normativeModel: [
      '- PR1 runtime formalization is job-level.',
      '- Runtime transition logic should be pure and replayable.',
      '- Temporal remains the durable execution host around semantic decisions.',
      '- Runtime input is expected to be normalized and statically validated before transition replay.',
    ],
    generatedLines: [
      '- Runtime state owner: `libs/api/workflows/src/core/runtime/runtime-state.ts`.',
      '- Runtime event owner: `libs/api/workflows/src/core/runtime/runtime-event.ts`.',
      '- Runtime command owner: `libs/api/workflows/src/core/runtime/runtime-command.ts`.',
      '- Runtime transition owner: `libs/api/workflows/src/core/runtime/transition.ts`.',
      '- Golden traces live under `libs/api/workflows/src/core/runtime/traces/`.',
      '- Runtime dependencies resolve against `RuntimeJobState.name`; `RuntimeJobState.id` identifies command targets.',
      renderRuntimeTypeReferenceGroup('Runtime State Reference', runtimeStateSource, [
        'RuntimeRunStatus',
        'RuntimeJobStatus',
        'RuntimeState',
        'RuntimeRunState',
        'RuntimeJobState',
      ]),
      renderRuntimeTypeReferenceGroup('Runtime Event Reference', runtimeEventSource, [
        'RuntimeEvent',
        'RunStartedEvent',
        'JobCompletedEvent',
      ]),
      renderRuntimeTypeReferenceGroup('Runtime Command Reference', runtimeCommandSource, [
        'RuntimeCommand',
        'StartJobCommand',
        'CancelJobCommand',
        'CompleteRunCommand',
      ]),
      renderRuntimeTransitionRuleReference(runtimeTransitionRuleReference),
      renderRuntimeGoldenTraceReference(),
      '- Wall-clock timeout remains a Temporal durable execution host concern and is intentionally absent from the pure transition kernel.',
    ],
    examples: ['A failed job cancels dependent jobs according to job-level dependency rules.'],
    addingOrChanging: [
      'Add transition metadata, golden traces, durable execution host updates, and docs in the same commit sequence.',
    ],
    deferredWork: ['- Step-level runtime transitions.', '- Runtime state snapshots.'],
  },
  {
    fileName: '007-durable-execution-host.md',
    title: '007 Durable Execution Host',
    status: 'normative',
    sourceOfTruth: 'libs/api/workflows/src/temporal/',
    purpose: [
      'Describe how Temporal and persistence adapt pure runtime commands to durable execution.',
    ],
    normativeModel: [
      '- Temporal is responsible for durability, timers, activities, and signal interpretation.',
      '- Runtime semantics belong in the pure kernel.',
      '- Temporal interprets runtime commands through child workflows and activities.',
      '- This layer is similar in spirit to a functional core / imperative shell, but Shipfox calls it the durable execution host to avoid confusion with shell-command steps.',
    ],
    generatedLines: [
      '- Durable execution host owner: `libs/api/workflows/src/temporal/workflows/run-orchestration.ts`.',
      '- Job execution host owner: `libs/api/workflows/src/temporal/workflows/job-orchestration.ts`.',
      '- Activity adapter owner: `libs/api/workflows/src/temporal/activities/orchestration-activities.ts`.',
      renderDurableExecutionHostCommandAdapterReference(),
      renderDurableExecutionHostWorkflowReference(),
      renderDurableExecutionHostActivityReference(),
      '- Job timeout remains in `jobOrchestration` and timeout activities.',
      '- Current run orchestration awaits each emitted `start_job` batch as a batch before processing downstream commands.',
    ],
    examples: [
      'Temporal can keep timeout handling while delegating readiness decisions to the kernel.',
    ],
    addingOrChanging: [
      'Update execution-host adapters and tests only when persistence, Temporal, outbox, runner, or trigger behavior changes.',
    ],
    deferredWork: [
      '- Runtime state snapshots.',
      '- Pipelined child workflow scheduling across sibling branches.',
    ],
  },
];

function renderBlock(lines: readonly string[]): string {
  return lines.length === 0 ? 'None.' : lines.join('\n\n');
}

function renderRuntimeTypeReferenceGroup(
  title: string,
  sourceText: string,
  typeNames: readonly string[],
): string {
  return [`### ${title}`, ...renderRuntimeTypeReferenceSections(sourceText, typeNames)].join(
    '\n\n',
  );
}

function renderRuntimeTransitionRuleReference(
  references: readonly RuntimeTransitionRuleReference[],
): string {
  const rows = references.map(
    (reference) => `| ${reference.rule} | ${reference.input} | ${reference.output} |`,
  );

  return [
    '### Runtime Transition Rule Summary',
    '',
    '| Rule | Input | Output |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderRuntimeGoldenTraceReference(): string {
  const rows = runtimeGoldenTraceReferences.map((reference) => {
    const trace = readRuntimeGoldenTrace(reference.fileName);
    const commandTypes = [
      ...new Set(trace.steps.flatMap((step) => step.commands.map((command) => command.type))),
    ];

    return `| \`${reference.fileName}\` | ${trace.name} | ${reference.purpose} | ${
      trace.initialState.jobs.length
    } | ${trace.steps.length} | ${trace.finalState.run.status} | ${commandTypes
      .map((type) => `\`${type}\``)
      .join(', ')} |`;
  });

  return [
    '### Runtime Golden Trace Reference',
    '',
    '| File | Trace Name | Purpose | Jobs | Steps | Final Run Status | Command Types |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderDurableExecutionHostCommandAdapterReference(): string {
  const rows = durableExecutionHostCommandAdapterReference.map(
    (reference) =>
      `| \`${reference.commandType}\` | ${reference.temporalOperation} | ${reference.owner} | ${reference.persistenceSideEffect} | ${reference.currentLimitation} |`,
  );

  return [
    '### Runtime Command Adapter Reference',
    '',
    '| Runtime Command | Temporal Operation | Owner | Persistence Side Effect | Current PR1 Limitation |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderDurableExecutionHostWorkflowReference(): string {
  const rows = durableExecutionHostWorkflowReference.map(
    (reference) => `| \`${reference.name}\` | ${reference.owner} | ${reference.role} |`,
  );

  return [
    '### Temporal Workflow Reference',
    '',
    '| Workflow | Owner | Role |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderDurableExecutionHostActivityReference(): string {
  const rows = durableExecutionHostActivityReference.map(
    (reference) => `| \`${reference.name}\` | ${reference.owner} | ${reference.sideEffect} |`,
  );

  return [
    '### Temporal Activity Reference',
    '',
    '| Activity | Owner | Side Effect |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function renderRuntimeFormalizationDoc(doc: RuntimeFormalizationDoc): string {
  const sections = [
    `# ${doc.title}`,
    `Status: ${doc.status}\nSource of truth: ${doc.sourceOfTruth}`,
    `## Purpose\n\n${renderBlock(doc.purpose)}`,
    `## Normative Model\n\n${renderBlock(doc.normativeModel)}\n\n${runtimeGeneratedSectionMarker}\n${runtimeGeneratedSectionStart}\n${renderBlock(doc.generatedLines)}\n${runtimeGeneratedSectionEnd}`,
    `## Examples\n\n${renderBlock(doc.examples)}`,
    `## Adding Or Changing This Concept\n\n${renderBlock(doc.addingOrChanging)}`,
    `## Deferred Work\n\n${renderBlock(doc.deferredWork)}`,
  ];

  return `${sections.join('\n\n')}\n`;
}

export function renderRuntimeFormalizationDocs(
  docs: readonly RuntimeFormalizationDoc[] = runtimeFormalizationDocs,
): ReadonlyMap<string, string> {
  return new Map(docs.map((doc) => [doc.fileName, renderRuntimeFormalizationDoc(doc)]));
}
