import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {
  readRuntimeGoldenTrace,
  runtimeGoldenTraceReferences,
} from '#core/runtime/runtime-golden-trace-reference.js';
import {
  durableExecutionHostActivityReference,
  durableExecutionHostCommandAdapterReference,
  durableExecutionHostWorkflowReference,
} from '#temporal/durable-execution-host-reference.js';
import {renderRuntimeTypeReferenceSections} from './runtime-typescript-reference.js';

export type RuntimeFormalizationDoc = Readonly<{
  fileName: string;
  title: string;
  status: 'normative';
  sourceOfTruth: string;
  purpose: readonly string[];
  normativeModel: readonly string[];
  generatedLines: readonly string[];
  examples: readonly string[];
  addingOrChanging: readonly string[];
  deferredWork: readonly string[];
  extraSections?: readonly RuntimeFormalizationDocSection[];
}>;

export const runtimeGeneratedSectionMarker =
  '<!-- generated by libs/api/workflows/scripts/generate-formalization-docs.ts; do not edit generated sections directly -->';

export const runtimeGeneratedSectionStart = '<!-- generated:start -->';
export const runtimeGeneratedSectionEnd = '<!-- generated:end -->';

type RuntimeTransitionRuleReference = Readonly<{
  rule: string;
  input: string;
  output: string;
}>;

type RuntimeFormalizationDocSection = Readonly<{
  title: string;
  body: readonly string[];
}>;

const runtimeStateSource = readFileSync(
  resolve(import.meta.dirname, '../core/runtime/runtime-state.ts'),
  'utf8',
);
const runtimeEventSource = readFileSync(
  resolve(import.meta.dirname, '../core/runtime/runtime-event.ts'),
  'utf8',
);
const runtimeCommandSource = readFileSync(
  resolve(import.meta.dirname, '../core/runtime/runtime-command.ts'),
  'utf8',
);

const runtimeTransitionRuleReference: readonly RuntimeTransitionRuleReference[] = [
  {
    rule: 'Terminal run guard',
    input: '`RuntimeState.run.status` is `succeeded` or `failed`.',
    output: 'Return a cloned state and emit no commands.',
  },
  {
    rule: '`run_started`',
    input: 'Run is not terminal.',
    output: 'Set run status to `running`, then reconcile jobs.',
  },
  {
    rule: '`job_completed`',
    input: 'Matching job exists and is `running`.',
    output: 'Set the job status to the event status, then reconcile jobs; otherwise no-op.',
  },
  {
    rule: 'Blocked pending jobs',
    input: 'Pending job depends on a failed or cancelled job.',
    output: 'Mark it `cancelled` and emit `cancel_job`.',
  },
  {
    rule: 'Ready pending jobs',
    input: 'Pending job has all dependencies `succeeded`.',
    output: 'Mark it `running` and emit `start_job`.',
  },
  {
    rule: 'No progress',
    input: 'Pending jobs remain, no job is running, and no job started.',
    output: 'Cancel remaining pending jobs.',
  },
  {
    rule: 'Terminal jobs',
    input: 'Every job is `succeeded`, `failed`, or `cancelled`.',
    output: 'Complete the run as `succeeded` only when no job failed or was cancelled.',
  },
];

export const runtimeFormalizationDocs: readonly RuntimeFormalizationDoc[] = [
  {
    fileName: '006-runtime-transitions.md',
    title: '006 Runtime Transitions',
    status: 'normative',
    sourceOfTruth: 'libs/api/workflows/src/core/runtime/',
    purpose: ['Document the pure job-level runtime transition system.'],
    normativeModel: [
      '- PR1 runtime formalization is job-level.',
      '- Runtime transition logic should be pure and replayable.',
      '- Temporal remains the durable execution host around semantic decisions.',
      '- Runtime input is expected to be normalized and statically validated before transition replay.',
    ],
    generatedLines: [
      '- Runtime state owner: `libs/api/workflows/src/core/runtime/runtime-state.ts`.',
      '- Runtime event owner: `libs/api/workflows/src/core/runtime/runtime-event.ts`.',
      '- Runtime command owner: `libs/api/workflows/src/core/runtime/runtime-command.ts`.',
      '- Runtime transition owner: `libs/api/workflows/src/core/runtime/transition.ts`.',
      '- Golden traces live under `libs/api/workflows/src/core/runtime/traces/`.',
      '- Runtime dependencies resolve against `RuntimeJobState.name`; `RuntimeJobState.id` identifies command targets.',
      renderRuntimeTypeReferenceGroup('Runtime State Reference', runtimeStateSource, [
        'RuntimeRunStatus',
        'RuntimeJobStatus',
        'RuntimeState',
        'RuntimeRunState',
        'RuntimeJobState',
      ]),
      renderRuntimeTypeReferenceGroup('Runtime Event Reference', runtimeEventSource, [
        'RuntimeEvent',
        'RunStartedEvent',
        'JobCompletedEvent',
      ]),
      renderRuntimeTypeReferenceGroup('Runtime Command Reference', runtimeCommandSource, [
        'RuntimeCommand',
        'StartJobCommand',
        'CancelJobCommand',
        'CompleteRunCommand',
      ]),
      renderRuntimeTransitionRuleReference(runtimeTransitionRuleReference),
      renderRuntimeGoldenTraceReference(),
      '- Wall-clock timeout remains a Temporal durable execution host concern and is intentionally absent from the pure transition kernel.',
    ],
    examples: ['A failed job cancels dependent jobs according to job-level dependency rules.'],
    addingOrChanging: [
      'Add transition metadata, golden traces, durable execution host updates, and docs in the same commit sequence.',
    ],
    deferredWork: ['- Step-level runtime transitions.', '- Runtime state snapshots.'],
    extraSections: [
      {
        title: 'Architecture Role',
        body: [
          'The pure runtime kernel is the semantic decision layer for workflow execution. It receives normalized runtime state and a runtime event, then returns the next state plus commands for the durable execution host to interpret.',
          'The kernel must stay independent from Temporal, PostgreSQL, runners, agents, GitHub, shell commands, clocks, queues, and network APIs. That boundary makes runtime behavior deterministic, replayable, and testable through unit tests and golden traces.',
          'PR1 keeps the kernel job-level: it decides when jobs start, when blocked jobs are cancelled, and when the run reaches a terminal status. Step-level execution, command execution, and external side effects remain outside this kernel.',
        ],
      },
      {
        title: 'Kernel Data Flow',
        body: [
          '```mermaid\nflowchart LR\n  ir["WorkflowIR"]\n  persisted["Persisted run, jobs, and dependencies"]\n  state["RuntimeState"]\n  event["RuntimeEvent"]\n  kernel["advanceRuntimeState<br/>pure transition kernel"]\n  next["Next RuntimeState"]\n  commands["RuntimeCommand[]"]\n  host["Durable execution host"]\n\n  ir --> persisted\n  persisted --> state\n  event --> kernel\n  state --> kernel\n  kernel --> next\n  kernel --> commands\n  commands --> host\n  host -. completion signals .-> event\n```',
        ],
      },
      {
        title: 'Kernel Responsibilities',
        body: [
          [
            '| Responsibility | Current PR1 Scope | Outside The Kernel |',
            '| --- | --- | --- |',
            '| Readiness | Start a pending job when all declared dependencies succeeded. | Selecting a physical runner or executing job steps. |',
            '| Blocking | Cancel pending jobs whose dependencies failed or were cancelled. | Force-stopping active runner work. |',
            '| Completion | Complete the run once every job is terminal. | Persisting the completion row or publishing events. |',
            '| Replayability | Produce deterministic commands from state and event. | Timers, retries, backoff, wall-clock reads, database writes, and network calls. |',
          ].join('\n'),
        ],
      },
    ],
  },
  {
    fileName: '007-durable-execution-host.md',
    title: '007 Durable Execution Host',
    status: 'normative',
    sourceOfTruth: 'libs/api/workflows/src/temporal/',
    purpose: [
      'Describe how Temporal and persistence adapt pure runtime commands to durable execution.',
    ],
    normativeModel: [
      '- Temporal is responsible for durability, timers, activities, and signal interpretation.',
      '- Runtime semantics belong in the pure kernel.',
      '- Temporal interprets runtime commands through child workflows and activities.',
      '- This layer is similar in spirit to a functional core / imperative shell, but Shipfox calls it the durable execution host to avoid confusion with shell-command steps.',
    ],
    generatedLines: [
      '- Durable execution host owner: `libs/api/workflows/src/temporal/workflows/run-orchestration.ts`.',
      '- Job execution host owner: `libs/api/workflows/src/temporal/workflows/job-orchestration.ts`.',
      '- Activity adapter owner: `libs/api/workflows/src/temporal/activities/orchestration-activities.ts`.',
      renderDurableExecutionHostCommandAdapterReference(),
      renderDurableExecutionHostWorkflowReference(),
      renderDurableExecutionHostActivityReference(),
      '- Job timeout remains in `jobOrchestration` and timeout activities.',
      '- Current run orchestration awaits each emitted `start_job` batch as a batch before processing downstream commands.',
    ],
    examples: [
      'Temporal can keep timeout handling while delegating readiness decisions to the kernel.',
    ],
    addingOrChanging: [
      'Update execution-host adapters and tests only when persistence, Temporal, outbox, runner, or trigger behavior changes.',
    ],
    deferredWork: [
      '- Runtime state snapshots.',
      '- Pipelined child workflow scheduling across sibling branches.',
    ],
    extraSections: [
      {
        title: 'Architecture Role',
        body: [
          'The durable execution host runs the pure runtime semantics in a reliable operational environment. It owns Temporal workflows, activities, persistence adapters, child workflow scheduling, timers, and future side-effect adapters.',
          'The host does not decide workflow semantics directly. It loads durable state, converts external signals into runtime events, invokes the pure kernel, persists the resulting state changes, and adapts emitted commands into Temporal or activity work.',
          'Runners sit behind this host boundary. A runner executes job work and reports completion; the durable host translates that completion into the next runtime event so the kernel can make the next semantic decision.',
        ],
      },
      {
        title: 'Execution Host Flow',
        body: [
          '```mermaid\nsequenceDiagram\n  participant Trigger as Trigger or API\n  participant Host as Durable execution host<br/>Temporal run orchestration\n  participant DB as PostgreSQL\n  participant Kernel as Pure runtime kernel\n  participant Job as Job orchestration\n  participant Runner as Runner or external system\n\n  Trigger->>Host: Start or signal workflow run\n  Host->>DB: Load persisted run state\n  Host->>Kernel: RuntimeState + RuntimeEvent\n  Kernel-->>Host: next state + RuntimeCommand[]\n  Host->>DB: Persist state transition\n  Host->>Job: Start child workflow for start_job\n  Job->>Runner: Execute job work\n  Runner-->>Job: Job completion\n  Job-->>Host: Completion signal\n  Host->>Kernel: job_completed event\n```',
        ],
      },
      {
        title: 'Main Components',
        body: [
          [
            '| Component | Role | Owned In |',
            '| --- | --- | --- |',
            '| Run orchestration workflow | Hosts the run loop, interprets runtime commands, starts child job workflows, and applies durable status updates. | `libs/api/workflows/src/temporal/workflows/run-orchestration.ts` |',
            '| Job orchestration workflow | Owns durable job execution, timeout handling, and job completion signaling. | `libs/api/workflows/src/temporal/workflows/job-orchestration.ts` |',
            '| Orchestration activities | Perform database reads and writes that the pure kernel cannot perform. | `libs/api/workflows/src/temporal/activities/orchestration-activities.ts` |',
            '| PostgreSQL workflow-run tables | Store normalized runs, jobs, dependencies, statuses, and versions derived from WorkflowIR. | `libs/api/workflows/src/db/` |',
            '| Runner boundary | Executes concrete job work and eventually reports completion or failure back through orchestration. | `apps/runner`, `libs/api/runners` |',
          ].join('\n'),
        ],
      },
    ],
  },
];

function renderBlock(lines: readonly string[]): string {
  return lines.length === 0 ? 'None.' : lines.join('\n\n');
}

function renderRuntimeTypeReferenceGroup(
  title: string,
  sourceText: string,
  typeNames: readonly string[],
): string {
  return [`### ${title}`, ...renderRuntimeTypeReferenceSections(sourceText, typeNames)].join(
    '\n\n',
  );
}

function renderRuntimeTransitionRuleReference(
  references: readonly RuntimeTransitionRuleReference[],
): string {
  const rows = references.map(
    (reference) => `| ${reference.rule} | ${reference.input} | ${reference.output} |`,
  );

  return [
    '### Runtime Transition Rule Summary',
    '',
    '| Rule | Input | Output |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderRuntimeGoldenTraceReference(): string {
  const rows = runtimeGoldenTraceReferences.map((reference) => {
    const trace = readRuntimeGoldenTrace(reference.fileName);
    const commandTypes = [
      ...new Set(trace.steps.flatMap((step) => step.commands.map((command) => command.type))),
    ];

    return `| \`${reference.fileName}\` | ${trace.name} | ${reference.purpose} | ${
      trace.initialState.jobs.length
    } | ${trace.steps.length} | ${trace.finalState.run.status} | ${commandTypes
      .map((type) => `\`${type}\``)
      .join(', ')} |`;
  });

  return [
    '### Runtime Golden Trace Reference',
    '',
    '| File | Trace Name | Purpose | Jobs | Steps | Final Run Status | Command Types |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderDurableExecutionHostCommandAdapterReference(): string {
  const rows = durableExecutionHostCommandAdapterReference.map(
    (reference) =>
      `| \`${reference.commandType}\` | ${reference.temporalOperation} | ${reference.owner} | ${reference.persistenceSideEffect} | ${reference.currentLimitation} |`,
  );

  return [
    '### Runtime Command Adapter Reference',
    '',
    '| Runtime Command | Temporal Operation | Owner | Persistence Side Effect | Current PR1 Limitation |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderDurableExecutionHostWorkflowReference(): string {
  const rows = durableExecutionHostWorkflowReference.map(
    (reference) => `| \`${reference.name}\` | ${reference.owner} | ${reference.role} |`,
  );

  return [
    '### Temporal Workflow Reference',
    '',
    '| Workflow | Owner | Role |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function renderDurableExecutionHostActivityReference(): string {
  const rows = durableExecutionHostActivityReference.map(
    (reference) => `| \`${reference.name}\` | ${reference.owner} | ${reference.sideEffect} |`,
  );

  return [
    '### Temporal Activity Reference',
    '',
    '| Activity | Owner | Side Effect |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function renderRuntimeFormalizationDoc(doc: RuntimeFormalizationDoc): string {
  const sections = [
    `# ${doc.title}`,
    `Status: ${doc.status}\nSource of truth: ${doc.sourceOfTruth}`,
    `## Purpose\n\n${renderBlock(doc.purpose)}`,
    `## Normative Model\n\n${renderBlock(doc.normativeModel)}\n\n${runtimeGeneratedSectionMarker}\n${runtimeGeneratedSectionStart}\n${renderBlock(doc.generatedLines)}\n${runtimeGeneratedSectionEnd}`,
    ...(doc.extraSections ?? []).map(
      (section) => `## ${section.title}\n\n${renderBlock(section.body)}`,
    ),
    `## Examples\n\n${renderBlock(doc.examples)}`,
    `## Adding Or Changing This Concept\n\n${renderBlock(doc.addingOrChanging)}`,
    `## Deferred Work\n\n${renderBlock(doc.deferredWork)}`,
  ];

  return `${sections.join('\n\n')}\n`;
}

export function renderRuntimeFormalizationDocs(
  docs: readonly RuntimeFormalizationDoc[] = runtimeFormalizationDocs,
): ReadonlyMap<string, string> {
  return new Map(docs.map((doc) => [doc.fileName, renderRuntimeFormalizationDoc(doc)]));
}
